### PR TITLE
fix(driver): fix bpf probe verifier on linux 5.14 and llvm 12.0.1

### LINKED ISSUE #58: Probe built with clang 10/11/12/13 does not load for 5.10/5.11/5.12 kernels
**Describe the bug**

When compiling the probe with a Clang 10/11/12 it succesfully compiles but fails to load.

I didn't investigate yet but wanted to give a reference to people having the same issue.

The workaround for now is to always compile using Clang 7.

<details>
<summary>verifier dump</summary>

```
program bpf_sys_readv_preadv_x: load program: permission denied: ; FILLER(sys_readv_preadv_x, true)\n0: (bf) r6 = r1\n1: (b7) r1 = 0\n; int id = 0;\n2: (63) *(u32 *)(r10 -80) = r1\nlast_idx 2 first_idx 0\nregs=2 stack=0 before 1: (b7) r1 = 0\n3: (bf) r2 = r10\n; \n4: (07) r2 += -80\n; settings = bpf_map_lookup_elem(&settings_map, &id);\n5: (18) r1 = 0xffff92dceb3af600\n7: (85) call bpf_map_lookup_elem#1\n8: (7b) *(u64 *)(r10 -88) = r0\n; if (!data->settings)\n9: (15) if r0 == 0x0 goto pc+3137\n R0_w=map_value(id=0,off=0,ks=4,vs=36,imm=0) R6_w=ctx(id=0,off=0,imm=0) R10=fp0 fp-80=????mmmm fp-88_w=map_value\n; cpu = bpf_get_smp_processor_id();\n10: (85) call bpf_get_smp_processor_id#8\n11: (bf) r8 = r0\n12: (63) *(u32 *)(r10 -80) = r8\n13: (bf) r2 = r10\n14: (07) r2 += -80\n; scratchp = bpf_map_lookup_elem(&frame_scratch_map, &cpu);\n15: (18) r1 = 0xffffa6ba50059000\n17: (85) call bpf_map_lookup_elem#1\n18: (bf) r9 = r0\n; if (!data->buf)\n19: (15) if r9 == 0x0 goto pc+3127\n R0_w=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R6=ctx(id=0,off=0,imm=0) R8_w=inv(id=2) R9_w=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value\n20: (63) *(u32 *)(r10 -80) = r8\n21: (bf) r2 = r10\n; \n22: (07) r2 += -80\n; state = bpf_map_lookup_elem(&local_state_map, &cpu);\n23: (18) r1 = 0xffff92db7254e000\n25: (85) call bpf_map_lookup_elem#1\n26: (bf) r7 = r0\n; if (!data->state)\n27: (15) if r7 == 0x0 goto pc+3119\n R0=map_value(id=0,off=0,ks=4,vs=77,imm=0) R6=ctx(id=0,off=0,imm=0) R7_w=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value\n28: (63) *(u32 *)(r10 -80) = r8\n29: (bf) r2 = r10\n; \n30: (07) r2 += -80\n; scratchp = bpf_map_lookup_elem(&tmp_scratch_map, &cpu);\n31: (18) r1 = 0xffffa6ba5065b000\n33: (85) call bpf_map_lookup_elem#1\n34: (18) r3 = 0xfffffffd\n36: (7b) *(u64 *)(r10 -96) = r0\n; if (!data->tmp_scratch)\n37: (15) if r0 == 0x0 goto pc+3100\n R0=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R3=inv4294967293 R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value\n; data->evt = get_event_info(data->state->tail_ctx.evt_type);\n38: (71) r1 = *(u8 *)(r7 +1)\n R0=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R3=inv4294967293 R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value\n39: (67) r1 <<= 8\n40: (71) r2 = *(u8 *)(r7 +0)\n R0=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R1_w=inv(id=0,umax_value=65280,var_off=(0x0; 0xff00)) R3=inv4294967293 R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value\n41: (4f) r1 |= r2\n42: (71) r2 = *(u8 *)(r7 +2)\n R0=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R1_w=inv(id=0) R2_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R3=inv4294967293 R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value\n43: (71) r3 = *(u8 *)(r7 +3)\n R0=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R1_w=inv(id=0) R2_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R3_w=inv4294967293 R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value\n44: (67) r3 <<= 8\n45: (4f) r3 |= r2\n46: (67) r3 <<= 16\n47: (4f) r3 |= r1\n48: (63) *(u32 *)(r10 -80) = r3\n49: (bf) r2 = r10\n50: (07) r2 += -80\n; bpf_map_lookup_elem(&event_info_table, &event_type);\n51: (18) r1 = 0xffffa6ba46575000\n53: (85) call bpf_map_lookup_elem#1\n54: (18) r3 = 0xfffffffd\n56: (7b) *(u64 *)(r10 -104) = r0\n; if (!data->evt)\n57: (15) if r0 == 0x0 goto pc+3080\n R0=map_value(id=0,off=0,ks=4,vs=1612,imm=0) R3_w=inv4294967293 R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104_w=map_value\n; data->filler_info = get_event_filler_info(data->state->tail_ctx.evt_type);\n58: (71) r1 = *(u8 *)(r7 +1)\n R0=map_value(id=0,off=0,ks=4,vs=1612,imm=0) R3_w=inv4294967293 R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104_w=map_value\n59: (67) r1 <<= 8\n60: (71) r2 = *(u8 *)(r7 +0)\n R0=map_value(id=0,off=0,ks=4,vs=1612,imm=0) R1_w=inv(id=0,umax_value=65280,var_off=(0x0; 0xff00)) R3_w=inv4294967293 R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104_w=map_value\n61: (4f) r1 |= r2\n62: (71) r2 = *(u8 *)(r7 +2)\n R0=map_value(id=0,off=0,ks=4,vs=1612,imm=0) R1_w=inv(id=0) R2_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R3_w=inv4294967293 R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104_w=map_value\n63: (71) r3 = *(u8 *)(r7 +3)\n R0=map_value(id=0,off=0,ks=4,vs=1612,imm=0) R1_w=inv(id=0) R2_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R3_w=inv4294967293 R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104_w=map_value\n64: (67) r3 <<= 8\n65: (4f) r3 |= r2\n66: (67) r3 <<= 16\n67: (4f) r3 |= r1\n68: (63) *(u32 *)(r10 -80) = r3\n69: (bf) r2 = r10\n70: (07) r2 += -80\n; e = bpf_map_lookup_elem(&fillers_table, &event_type);\n71: (18) r1 = 0xffff92dcf7888000\n73: (85) call bpf_map_lookup_elem#1\n74: (18) r3 = 0xfffffffd\n; if (!data->filler_info)\n76: (15) if r0 == 0x0 goto pc+3061\n R0=map_value(id=0,off=0,ks=4,vs=58,imm=0) R3_w=inv4294967293 R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value\n; FILLER(sys_readv_preadv_x, true)\n77: (71) r1 = *(u8 *)(r7 +29)\n R0=map_value(id=0,off=0,ks=4,vs=58,imm=0) R3_w=inv4294967293 R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value\n78: (67) r1 <<= 8\n79: (71) r2 = *(u8 *)(r7 +28)\n R0=map_value(id=0,off=0,ks=4,vs=58,imm=0) R1_w=inv(id=0,umax_value=65280,var_off=(0x0; 0xff00)) R3_w=inv4294967293 R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value\n80: (4f) r1 |= r2\n81: (71) r2 = *(u8 *)(r7 +31)\n R0=map_value(id=0,off=0,ks=4,vs=58,imm=0) R1_w=inv(id=0) R2_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R3_w=inv4294967293 R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value\n82: (67) r2 <<= 8\n83: (71) r3 = *(u8 *)(r7 +30)\n R0=map_value(id=0,off=0,ks=4,vs=58,imm=0) R1_w=inv(id=0) R2_w=inv(id=0,umax_value=65280,var_off=(0x0; 0xff00)) R3_w=inv4294967293 R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value\n84: (4f) r2 |= r3\n85: (67) r2 <<= 16\n86: (4f) r2 |= r1\n87: (71) r3 = *(u8 *)(r7 +33)\n R0=map_value(id=0,off=0,ks=4,vs=58,imm=0) R1_w=inv(id=0) R2_w=inv(id=0) R3_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value\n88: (67) r3 <<= 8\n89: (71) r1 = *(u8 *)(r7 +32)\n R0=map_value(id=0,off=0,ks=4,vs=58,imm=0) R1_w=inv(id=0) R2_w=inv(id=0) R3_w=inv(id=0,umax_value=65280,var_off=(0x0; 0xff00)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value\n90: (4f) r3 |= r1\n91: (71) r4 = *(u8 *)(r7 +34)\n R0=map_value(id=0,off=0,ks=4,vs=58,imm=0) R1_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R2_w=inv(id=0) R3_w=inv(id=0) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value\n92: (71) r1 = *(u8 *)(r7 +35)\n R0=map_value(id=0,off=0,ks=4,vs=58,imm=0) R1_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R2_w=inv(id=0) R3_w=inv(id=0) R4_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value\n93: (67) r1 <<= 8\n94: (4f) r1 |= r4\n95: (67) r1 <<= 16\n96: (4f) r1 |= r3\n97: (67) r1 <<= 32\n98: (4f) r1 |= r2\n; FILLER(sys_readv_preadv_x, true)\n99: (15) if r1 == 0x0 goto pc+26\n R0=map_value(id=0,off=0,ks=4,vs=58,imm=0) R1_w=inv(id=0) R2_w=inv(id=0) R3_w=inv(id=0) R4_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value\n; if (data->state->tail_ctx.curoff > SCRATCH_SIZE_HALF)\n100: (71) r2 = *(u8 *)(r7 +21)\n R0=map_value(id=0,off=0,ks=4,vs=58,imm=0) R1_w=inv(id=0) R2_w=inv(id=0) R3_w=inv(id=0) R4_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value\n101: (67) r2 <<= 8\n102: (71) r3 = *(u8 *)(r7 +20)\n R0=map_value(id=0,off=0,ks=4,vs=58,imm=0) R1_w=inv(id=0) R2_w=inv(id=0,umax_value=65280,var_off=(0x0; 0xff00)) R3_w=inv(id=0) R4_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value\n103: (4f) r2 |= r3\n104: (71) r3 = *(u8 *)(r7 +23)\n R0=map_value(id=0,off=0,ks=4,vs=58,imm=0) R1_w=inv(id=0) R2_w=inv(id=0) R3_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R4_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value\n105: (67) r3 <<= 8\n106: (71) r4 = *(u8 *)(r7 +22)\n R0=map_value(id=0,off=0,ks=4,vs=58,imm=0) R1_w=inv(id=0) R2_w=inv(id=0) R3_w=inv(id=0,umax_value=65280,var_off=(0x0; 0xff00)) R4_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value\n107: (4f) r3 |= r4\n108: (67) r3 <<= 16\n109: (4f) r3 |= r2\n110: (71) r4 = *(u8 *)(r7 +25)\n R0=map_value(id=0,off=0,ks=4,vs=58,imm=0) R1_w=inv(id=0) R2_w=inv(id=0) R3_w=inv(id=0) R4_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value\n111: (67) r4 <<= 8\n112: (71) r2 = *(u8 *)(r7 +24)\n R0=map_value(id=0,off=0,ks=4,vs=58,imm=0) R1_w=inv(id=0) R2_w=inv(id=0) R3_w=inv(id=0) R4_w=inv(id=0,umax_value=65280,var_off=(0x0; 0xff00)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value\n113: (4f) r4 |= r2\n114: (71) r2 = *(u8 *)(r7 +27)\n R0=map_value(id=0,off=0,ks=4,vs=58,imm=0) R1_w=inv(id=0) R2_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R3_w=inv(id=0) R4_w=inv(id=0) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value\n115: (67) r2 <<= 8\n116: (71) r5 = *(u8 *)(r7 +26)\n R0=map_value(id=0,off=0,ks=4,vs=58,imm=0) R1_w=inv(id=0) R2_w=inv(id=0,umax_value=65280,var_off=(0x0; 0xff00)) R3_w=inv(id=0) R4_w=inv(id=0) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value\n117: (4f) r2 |= r5\n118: (67) r2 <<= 16\n119: (4f) r2 |= r4\n120: (67) r2 <<= 32\n121: (4f) r2 |= r3\n122: (bf) r3 = r7\n123: (07) r3 += 20\n124: (7b) *(u64 *)(r10 -120) = r3\n125: (05) goto pc+90\n; if (data->state->tail_ctx.curoff > SCRATCH_SIZE_HALF)\n216: (18) r3 = 0xffffffff\n; if (data->state->tail_ctx.curoff > SCRATCH_SIZE_HALF)\n218: (25) if r2 > 0x1ffff goto pc+2919\n R0=map_value(id=0,off=0,ks=4,vs=58,imm=0) R1=inv(id=0) R2=inv(id=0,umax_value=131071,var_off=(0x0; 0xffffffff)) R3_w=inv4294967295 R4=inv(id=0) R5=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-120=map_value\n; \n219: (79) r4 = *(u64 *)(r6 +8)\n; *((s64 *)&data->buf[data->state->tail_ctx.curoff & SCRATCH_SIZE_HALF]) = val;\n220: (bf) r3 = r9\n221: (0f) r3 += r2\nlast_idx 221 first_idx 216\nregs=4 stack=0 before 220: (bf) r3 = r9\nregs=4 stack=0 before 219: (79) r4 = *(u64 *)(r6 +8)\nregs=4 stack=0 before 218: (25) if r2 > 0x1ffff goto pc+2919\nregs=4 stack=0 before 216: (18) r3 = 0xffffffff\n R0=map_value(id=0,off=0,ks=4,vs=58,imm=0) R1_w=inv(id=0) R2_rw=invP(id=0) R3_w=map_value(id=0,off=20,ks=4,vs=77,imm=0) R4_w=inv(id=0) R5_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6_r=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9_r=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-120_w=map_value\nparent didn't have regs=4 stack=0 marks\nlast_idx 125 first_idx 74\nregs=4 stack=0 before 125: (05) goto pc+90\nregs=4 stack=0 before 124: (7b) *(u64 *)(r10 -120) = r3\nregs=4 stack=0 before 123: (07) r3 += 20\nregs=4 stack=0 before 122: (bf) r3 = r7\nregs=4 stack=0 before 121: (4f) r2 |= r3\nregs=c stack=0 before 120: (67) r2 <<= 32\nregs=c stack=0 before 119: (4f) r2 |= r4\nregs=1c stack=0 before 118: (67) r2 <<= 16\nregs=1c stack=0 before 117: (4f) r2 |= r5\nregs=3c stack=0 before 116: (71) r5 = *(u8 *)(r7 +26)\nregs=1c stack=0 before 115: (67) r2 <<= 8\nregs=1c stack=0 before 114: (71) r2 = *(u8 *)(r7 +27)\nregs=18 stack=0 before 113: (4f) r4 |= r2\nregs=1c stack=0 before 112: (71) r2 = *(u8 *)(r7 +24)\nregs=18 stack=0 before 111: (67) r4 <<= 8\nregs=18 stack=0 before 110: (71) r4 = *(u8 *)(r7 +25)\nregs=8 stack=0 before 109: (4f) r3 |= r2\nregs=c stack=0 before 108: (67) r3 <<= 16\nregs=c stack=0 before 107: (4f) r3 |= r4\nregs=1c stack=0 before 106: (71) r4 = *(u8 *)(r7 +22)\nregs=c stack=0 before 105: (67) r3 <<= 8\nregs=c stack=0 before 104: (71) r3 = *(u8 *)(r7 +23)\nregs=4 stack=0 before 103: (4f) r2 |= r3\nregs=c stack=0 before 102: (71) r3 = *(u8 *)(r7 +20)\nregs=4 stack=0 before 101: (67) r2 <<= 8\nregs=4 stack=0 before 100: (71) r2 = *(u8 *)(r7 +21)\n222: (7b) *(u64 *)(r10 -128) = r4\n; *((s64 *)&data->buf[data->state->tail_ctx.curoff & SCRATCH_SIZE_HALF]) = val;\n223: (7b) *(u64 *)(r3 +0) = r4\n R0=map_value(id=0,off=0,ks=4,vs=58,imm=0) R1=inv(id=0) R2=invP(id=0,umax_value=131071,var_off=(0x0; 0xffffffff)) R3_w=map_value(id=0,off=0,ks=4,vs=262144,umax_value=131071,var_off=(0x0; 0xffffffff)) R4_w=inv(id=0) R5=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-120=map_value fp-128_w=mmmmmmmm\n; fixup_evt_arg_len(data->buf, data->state->tail_ctx.curarg, len_dyn + len);\n224: (71) r3 = *(u8 *)(r7 +13)\n R0=map_value(id=0,off=0,ks=4,vs=58,imm=0) R1=inv(id=0) R2=invP(id=0,umax_value=131071,var_off=(0x0; 0xffffffff)) R3_w=map_value(id=0,off=0,ks=4,vs=262144,umax_value=131071,var_off=(0x0; 0xffffffff)) R4_w=inv(id=0) R5=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-120=map_value fp-128_w=mmmmmmmm\n225: (67) r3 <<= 8\n226: (71) r4 = *(u8 *)(r7 +12)\n R0=map_value(id=0,off=0,ks=4,vs=58,imm=0) R1=inv(id=0) R2=invP(id=0,umax_value=131071,var_off=(0x0; 0xffffffff)) R3_w=inv(id=0,umax_value=65280,var_off=(0x0; 0xff00)) R4_w=inv(id=0) R5=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-120=map_value fp-128_w=mmmmmmmm\n227: (4f) r3 |= r4\n228: (71) r4 = *(u8 *)(r7 +15)\n R0=map_value(id=0,off=0,ks=4,vs=58,imm=0) R1=inv(id=0) R2=invP(id=0,umax_value=131071,var_off=(0x0; 0xffffffff)) R3_w=inv(id=0) R4_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R5=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-120=map_value fp-128_w=mmmmmmmm\n229: (67) r4 <<= 8\n230: (71) r5 = *(u8 *)(r7 +14)\n R0=map_value(id=0,off=0,ks=4,vs=58,imm=0) R1=inv(id=0) R2=invP(id=0,umax_value=131071,var_off=(0x0; 0xffffffff)) R3_w=inv(id=0) R4_w=inv(id=0,umax_value=65280,var_off=(0x0; 0xff00)) R5_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-120=map_value fp-128_w=mmmmmmmm\n231: (4f) r4 |= r5\n232: (67) r4 <<= 16\n233: (4f) r4 |= r3\n234: (71) r5 = *(u8 *)(r7 +17)\n R0=map_value(id=0,off=0,ks=4,vs=58,imm=0) R1=inv(id=0) R2=invP(id=0,umax_value=131071,var_off=(0x0; 0xffffffff)) R3_w=inv(id=0) R4_w=inv(id=0) R5_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-120=map_value fp-128_w=mmmmmmmm\n235: (67) r5 <<= 8\n236: (71) r3 = *(u8 *)(r7 +16)\n R0=map_value(id=0,off=0,ks=4,vs=58,imm=0) R1=inv(id=0) R2=invP(id=0,umax_value=131071,var_off=(0x0; 0xffffffff)) R3_w=inv(id=0) R4_w=inv(id=0) R5_w=inv(id=0,umax_value=65280,var_off=(0x0; 0xff00)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-120=map_value fp-128_w=mmmmmmmm\n237: (4f) r5 |= r3\n238: (71) r0 = *(u8 *)(r7 +18)\n R0_w=map_value(id=0,off=0,ks=4,vs=58,imm=0) R1=inv(id=0) R2=invP(id=0,umax_value=131071,var_off=(0x0; 0xffffffff)) R3_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R4_w=inv(id=0) R5_w=inv(id=0) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-120=map_value fp-128_w=mmmmmmmm\n239: (71) r3 = *(u8 *)(r7 +19)\n R0_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R1=inv(id=0) R2=invP(id=0,umax_value=131071,var_off=(0x0; 0xffffffff)) R3_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R4_w=inv(id=0) R5_w=inv(id=0) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-120=map_value fp-128_w=mmmmmmmm\n240: (67) r3 <<= 8\n241: (4f) r3 |= r0\n242: (67) r3 <<= 16\n243: (4f) r3 |= r5\n244: (67) r3 <<= 32\n245: (4f) r3 |= r4\n; fixup_evt_arg_len(data->buf, data->state->tail_ctx.curarg, len_dyn + len);\n246: (bf) r4 = r3\n247: (67) r4 <<= 32\n248: (77) r4 >>= 32\n; if (argnum > PPM_MAX_EVENT_PARAMS)\n249: (25) if r4 > 0x20 goto pc+8\n R0_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R1=inv(id=0) R2=invP(id=0,umax_value=131071,var_off=(0x0; 0xffffffff)) R3_w=inv(id=8) R4_w=inv(id=0,umax_value=32,var_off=(0x0; 0xffffffff)) R5_w=inv(id=0) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-120=map_value fp-128_w=mmmmmmmm\n; volatile unsigned int argnumv = argnum;\n250: (63) *(u32 *)(r10 -80) = r3\n; *((u16 *)&p[sizeof(struct ppm_evt_hdr)] + (argnumv & (PPM_MAX_EVENT_PARAMS - 1))) = arglen;\n251: (61) r4 = *(u32 *)(r10 -80)\n; *((u16 *)&p[sizeof(struct ppm_evt_hdr)] + (argnumv & (PPM_MAX_EVENT_PARAMS - 1))) = arglen;\n252: (57) r4 &= 31\n253: (67) r4 <<= 1\n; *((u16 *)&p[sizeof(struct ppm_evt_hdr)] + (argnumv & (PPM_MAX_EVENT_PARAMS - 1))) = arglen;\n254: (bf) r5 = r9\n255: (0f) r5 += r4\nlast_idx 255 first_idx 216\nregs=10 stack=0 before 254: (bf) r5 = r9\nregs=10 stack=0 before 253: (67) r4 <<= 1\nregs=10 stack=0 before 252: (57) r4 &= 31\nregs=10 stack=0 before 251: (61) r4 = *(u32 *)(r10 -80)\n256: (b7) r4 = 8\n; *((u16 *)&p[sizeof(struct ppm_evt_hdr)] + (argnumv & (PPM_MAX_EVENT_PARAMS - 1))) = arglen;\n257: (6b) *(u16 *)(r5 +26) = r4\n R0_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R1=inv(id=0) R2=invP(id=0,umax_value=131071,var_off=(0x0; 0xffffffff)) R3_w=inv(id=8) R4_w=inv8 R5_w=map_value(id=0,off=0,ks=4,vs=262144,umax_value=62,var_off=(0x0; 0x3e)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-120=map_value fp-128_w=mmmmmmmm\n; data->state->tail_ctx.len += len;\n258: (07) r1 += 8\n259: (bf) r4 = r1\n260: (77) r4 >>= 56\n261: (73) *(u8 *)(r7 +35) = r4\n R0=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R1_w=inv(id=9) R2=invP(id=0,umax_value=131071,var_off=(0x0; 0xffffffff)) R3=inv(id=8) R4_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R5=map_value(id=0,off=0,ks=4,vs=262144,umax_value=62,var_off=(0x0; 0x3e)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-120=map_value fp-128=mmmmmmmm\n262: (bf) r4 = r1\n263: (77) r4 >>= 48\n264: (73) *(u8 *)(r7 +34) = r4\n R0=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R1_w=inv(id=9) R2=invP(id=0,umax_value=131071,var_off=(0x0; 0xffffffff)) R3=inv(id=8) R4_w=inv(id=0,umax_value=65535,var_off=(0x0; 0xffff)) R5=map_value(id=0,off=0,ks=4,vs=262144,umax_value=62,var_off=(0x0; 0x3e)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-120=map_value fp-128=mmmmmmmm\n265: (bf) r4 = r1\n266: (77) r4 >>= 40\n267: (73) *(u8 *)(r7 +33) = r4\n R0=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R1_w=inv(id=9) R2=invP(id=0,umax_value=131071,var_off=(0x0; 0xffffffff)) R3=inv(id=8) R4_w=inv(id=0,umax_value=16777215,var_off=(0x0; 0xffffff)) R5=map_value(id=0,off=0,ks=4,vs=262144,umax_value=62,var_off=(0x0; 0x3e)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-120=map_value fp-128=mmmmmmmm\n268: (bf) r4 = r1\n269: (77) r4 >>= 32\n270: (73) *(u8 *)(r7 +32) = r4\n R0=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R1_w=inv(id=9) R2=invP(id=0,umax_value=131071,var_off=(0x0; 0xffffffff)) R3=inv(id=8) R4_w=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R5=map_value(id=0,off=0,ks=4,vs=262144,umax_value=62,var_off=(0x0; 0x3e)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-120=map_value fp-128=mmmmmmmm\n271: (bf) r4 = r1\n272: (77) r4 >>= 24\n273: (73) *(u8 *)(r7 +31) = r4\n R0=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R1_w=inv(id=9) R2=invP(id=0,umax_value=131071,var_off=(0x0; 0xffffffff)) R3=inv(id=8) R4_w=inv(id=0,umax_value=1099511627775,var_off=(0x0; 0xffffffffff)) R5=map_value(id=0,off=0,ks=4,vs=262144,umax_value=62,var_off=(0x0; 0x3e)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-120=map_value fp-128=mmmmmmmm\n274: (bf) r4 = r1\n275: (77) r4 >>= 16\n276: (73) *(u8 *)(r7 +30) = r4\n R0=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R1_w=inv(id=9) R2=invP(id=0,umax_value=131071,var_off=(0x0; 0xffffffff)) R3=inv(id=8) R4_w=inv(id=0,umax_value=281474976710655,var_off=(0x0; 0xffffffffffff)) R5=map_value(id=0,off=0,ks=4,vs=262144,umax_value=62,var_off=(0x0; 0x3e)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-120=map_value fp-128=mmmmmmmm\n277: (73) *(u8 *)(r7 +28) = r1\n R0=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R1_w=inv(id=9) R2=invP(id=0,umax_value=131071,var_off=(0x0; 0xffffffff)) R3=inv(id=8) R4_w=inv(id=0,umax_value=281474976710655,var_off=(0x0; 0xffffffffffff)) R5=map_value(id=0,off=0,ks=4,vs=262144,umax_value=62,var_off=(0x0; 0x3e)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-120=map_value fp-128=mmmmmmmm\n278: (77) r1 >>= 8\n279: (73) *(u8 *)(r7 +29) = r1\n R0=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R1_w=inv(id=0,umax_value=72057594037927935,var_off=(0x0; 0xffffffffffffff)) R2=invP(id=0,umax_value=131071,var_off=(0x0; 0xffffffff)) R3=inv(id=8) R4_w=inv(id=0,umax_value=281474976710655,var_off=(0x0; 0xffffffffffff)) R5=map_value(id=0,off=0,ks=4,vs=262144,umax_value=62,var_off=(0x0; 0x3e)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-120=map_value fp-128=mmmmmmmm\n; data->state->tail_ctx.curoff += len;\n280: (07) r2 += 8\n281: (bf) r1 = r2\n282: (77) r1 >>= 56\n283: (73) *(u8 *)(r7 +27) = r1\n R0=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R1_w=invP0 R2_w=invP(id=10,umin_value=8,umax_value=131079,var_off=(0x0; 0xffffffff)) R3=inv(id=8) R4_w=inv(id=0,umax_value=281474976710655,var_off=(0x0; 0xffffffffffff)) R5=map_value(id=0,off=0,ks=4,vs=262144,umax_value=62,var_off=(0x0; 0x3e)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-120=map_value fp-128=mmmmmmmm\n284: (bf) r1 = r2\n285: (77) r1 >>= 48\n286: (73) *(u8 *)(r7 +26) = r1\n R0=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R1_w=invP0 R2_w=invP(id=10,umin_value=8,umax_value=131079,var_off=(0x0; 0xffffffff)) R3=inv(id=8) R4_w=inv(id=0,umax_value=281474976710655,var_off=(0x0; 0xffffffffffff)) R5=map_value(id=0,off=0,ks=4,vs=262144,umax_value=62,var_off=(0x0; 0x3e)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-120=map_value fp-128=mmmmmmmm\n287: (bf) r1 = r2\n288: (77) r1 >>= 40\n289: (73) *(u8 *)(r7 +25) = r1\n R0=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R1_w=invP0 R2_w=invP(id=10,umin_value=8,umax_value=131079,var_off=(0x0; 0xffffffff)) R3=inv(id=8) R4_w=inv(id=0,umax_value=281474976710655,var_off=(0x0; 0xffffffffffff)) R5=map_value(id=0,off=0,ks=4,vs=262144,umax_value=62,var_off=(0x0; 0x3e)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-120=map_value fp-128=mmmmmmmm\n290: (bf) r1 = r2\n291: (77) r1 >>= 32\n292: (73) *(u8 *)(r7 +24) = r1\n R0=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R1_w=invP0 R2_w=invP(id=10,umin_value=8,umax_value=131079,var_off=(0x0; 0xffffffff)) R3=inv(id=8) R4_w=inv(id=0,umax_value=281474976710655,var_off=(0x0; 0xffffffffffff)) R5=map_value(id=0,off=0,ks=4,vs=262144,umax_value=62,var_off=(0x0; 0x3e)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-120=map_value fp-128=mmmmmmmm\n293: (bf) r1 = r2\n294: (77) r1 >>= 24\n295: (73) *(u8 *)(r7 +23) = r1\n R0=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R1_w=invP(id=0,umax_value=0,var_off=(0x0; 0xff),s32_max_value=255,u32_max_value=255) R2_w=invP(id=10,umin_value=8,umax_value=131079,var_off=(0x0; 0xffffffff)) R3=inv(id=8) R4_w=inv(id=0,umax_value=281474976710655,var_off=(0x0; 0xffffffffffff)) R5=map_value(id=0,off=0,ks=4,vs=262144,umax_value=62,var_off=(0x0; 0x3e)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-120=map_value fp-128=mmmmmmmm\n296: (bf) r1 = r2\n297: (77) r1 >>= 16\n298: (73) *(u8 *)(r7 +22) = r1\n R0=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R1_w=invP(id=0,umax_value=2,var_off=(0x0; 0xffff),s32_max_value=65535,u32_max_value=65535) R2_w=invP(id=10,umin_value=8,umax_value=131079,var_off=(0x0; 0xffffffff)) R3=inv(id=8) R4_w=inv(id=0,umax_value=281474976710655,var_off=(0x0; 0xffffffffffff)) R5=map_value(id=0,off=0,ks=4,vs=262144,umax_value=62,var_off=(0x0; 0x3e)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-120=map_value fp-128=mmmmmmmm\n299: (73) *(u8 *)(r7 +20) = r2\n R0=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R1_w=invP(id=0,umax_value=2,var_off=(0x0; 0xffff),s32_max_value=65535,u32_max_value=65535) R2_w=invP(id=10,umin_value=8,umax_value=131079,var_off=(0x0; 0xffffffff)) R3=inv(id=8) R4_w=inv(id=0,umax_value=281474976710655,var_off=(0x0; 0xffffffffffff)) R5=map_value(id=0,off=0,ks=4,vs=262144,umax_value=62,var_off=(0x0; 0x3e)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-120=map_value fp-128=mmmmmmmm\n300: (77) r2 >>= 8\n301: (73) *(u8 *)(r7 +21) = r2\n R0=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R1_w=invP(id=0,umax_value=2,var_off=(0x0; 0xffff),s32_max_value=65535,u32_max_value=65535) R2_w=invP(id=0,umax_value=512,var_off=(0x0; 0xffffff),s32_max_value=16777215,u32_max_value=16777215) R3=inv(id=8) R4_w=inv(id=0,umax_value=281474976710655,var_off=(0x0; 0xffffffffffff)) R5=map_value(id=0,off=0,ks=4,vs=262144,umax_value=62,var_off=(0x0; 0x3e)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-120=map_value fp-128=mmmmmmmm\n; ++data->state->tail_ctx.curarg;\n302: (07) r3 += 1\n303: (bf) r1 = r3\n304: (77) r1 >>= 56\n305: (73) *(u8 *)(r7 +19) = r1\n R0=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R1_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R2_w=invP(id=0,umax_value=512,var_off=(0x0; 0xffffff),s32_max_value=16777215,u32_max_value=16777215) R3_w=inv(id=11) R4_w=inv(id=0,umax_value=281474976710655,var_off=(0x0; 0xffffffffffff)) R5=map_value(id=0,off=0,ks=4,vs=262144,umax_value=62,var_off=(0x0; 0x3e)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-120=map_value fp-128=mmmmmmmm\n306: (bf) r1 = r3\n307: (77) r1 >>= 48\n308: (73) *(u8 *)(r7 +18) = r1\n R0=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R1_w=inv(id=0,umax_value=65535,var_off=(0x0; 0xffff)) R2_w=invP(id=0,umax_value=512,var_off=(0x0; 0xffffff),s32_max_value=16777215,u32_max_value=16777215) R3_w=inv(id=11) R4_w=inv(id=0,umax_value=281474976710655,var_off=(0x0; 0xffffffffffff)) R5=map_value(id=0,off=0,ks=4,vs=262144,umax_value=62,var_off=(0x0; 0x3e)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-120=map_value fp-128=mmmmmmmm\n309: (bf) r1 = r3\n310: (77) r1 >>= 40\n311: (73) *(u8 *)(r7 +17) = r1\n R0=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R1_w=inv(id=0,umax_value=16777215,var_off=(0x0; 0xffffff)) R2_w=invP(id=0,umax_value=512,var_off=(0x0; 0xffffff),s32_max_value=16777215,u32_max_value=16777215) R3_w=inv(id=11) R4_w=inv(id=0,umax_value=281474976710655,var_off=(0x0; 0xffffffffffff)) R5=map_value(id=0,off=0,ks=4,vs=262144,umax_value=62,var_off=(0x0; 0x3e)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-120=map_value fp-128=mmmmmmmm\n312: (bf) r1 = r3\n313: (77) r1 >>= 32\n314: (73) *(u8 *)(r7 +16) = r1\n R0=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R1_w=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R2_w=invP(id=0,umax_value=512,var_off=(0x0; 0xffffff),s32_max_value=16777215,u32_max_value=16777215) R3_w=inv(id=11) R4_w=inv(id=0,umax_value=281474976710655,var_off=(0x0; 0xffffffffffff)) R5=map_value(id=0,off=0,ks=4,vs=262144,umax_value=62,var_off=(0x0; 0x3e)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-120=map_value fp-128=mmmmmmmm\n315: (bf) r1 = r3\n316: (77) r1 >>= 24\n317: (73) *(u8 *)(r7 +15) = r1\n R0=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R1_w=inv(id=0,umax_value=1099511627775,var_off=(0x0; 0xffffffffff)) R2_w=invP(id=0,umax_value=512,var_off=(0x0; 0xffffff),s32_max_value=16777215,u32_max_value=16777215) R3_w=inv(id=11) R4_w=inv(id=0,umax_value=281474976710655,var_off=(0x0; 0xffffffffffff)) R5=map_value(id=0,off=0,ks=4,vs=262144,umax_value=62,var_off=(0x0; 0x3e)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-120=map_value fp-128=mmmmmmmm\n318: (bf) r1 = r3\n319: (77) r1 >>= 16\n320: (73) *(u8 *)(r7 +14) = r1\n R0=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R1_w=inv(id=0,umax_value=281474976710655,var_off=(0x0; 0xffffffffffff)) R2_w=invP(id=0,umax_value=512,var_off=(0x0; 0xffffff),s32_max_value=16777215,u32_max_value=16777215) R3_w=inv(id=11) R4_w=inv(id=0,umax_value=281474976710655,var_off=(0x0; 0xffffffffffff)) R5=map_value(id=0,off=0,ks=4,vs=262144,umax_value=62,var_off=(0x0; 0x3e)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-120=map_value fp-128=mmmmmmmm\n321: (73) *(u8 *)(r7 +12) = r3\n R0=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R1_w=inv(id=0,umax_value=281474976710655,var_off=(0x0; 0xffffffffffff)) R2_w=invP(id=0,umax_value=512,var_off=(0x0; 0xffffff),s32_max_value=16777215,u32_max_value=16777215) R3_w=inv(id=11) R4_w=inv(id=0,umax_value=281474976710655,var_off=(0x0; 0xffffffffffff)) R5=map_value(id=0,off=0,ks=4,vs=262144,umax_value=62,var_off=(0x0; 0x3e)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-120=map_value fp-128=mmmmmmmm\n322: (77) r3 >>= 8\n323: (73) *(u8 *)(r7 +13) = r3\n R0=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R1_w=inv(id=0,umax_value=281474976710655,var_off=(0x0; 0xffffffffffff)) R2_w=invP(id=0,umax_value=512,var_off=(0x0; 0xffffff),s32_max_value=16777215,u32_max_value=16777215) R3_w=inv(id=0,umax_value=72057594037927935,var_off=(0x0; 0xffffffffffffff)) R4_w=inv(id=0,umax_value=281474976710655,var_off=(0x0; 0xffffffffffff)) R5=map_value(id=0,off=0,ks=4,vs=262144,umax_value=62,var_off=(0x0; 0x3e)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=2) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=????mmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-120=map_value fp-128=mmmmmmmm\n; struct pt_regs *regs = (struct pt_regs *)args->regs;\n324: (79) r3 = *(u64 *)(r6 +0)\n325: (7b) *(u64 *)(r10 -112) = r6\n326: (b7) r6 = 0\n; arg = _READ(regs->si);\n327: (7b) *(u64 *)(r10 -80) = r6\nlast_idx 327 first_idx 258\nregs=40 stack=0 before 326: (b7) r6 = 0\n328: (07) r3 += 104\n329: (bf) r1 = r10\n; \n330: (07) r1 += -80\n; arg = _READ(regs->si);\n331: (b7) r2 = 8\n332: (85) call bpf_probe_read#4\nlast_idx 332 first_idx 258\nregs=4 stack=0 before 331: (b7) r2 = 8\n333: (79) r8 = *(u64 *)(r10 -80)\n; struct pt_regs *regs = (struct pt_regs *)args->regs;\n334: (79) r1 = *(u64 *)(r10 -112)\n335: (79) r3 = *(u64 *)(r1 +0)\n; arg = _READ(regs->dx);\n336: (7b) *(u64 *)(r10 -80) = r6\n337: (79) r6 = *(u64 *)(r10 -112)\n338: (07) r3 += 96\n339: (bf) r1 = r10\n; \n340: (07) r1 += -80\n; arg = _READ(regs->dx);\n341: (b7) r2 = 8\n342: (85) call bpf_probe_read#4\nlast_idx 342 first_idx 258\nregs=4 stack=0 before 341: (b7) r2 = 8\n343: (79) r2 = *(u64 *)(r10 -80)\n344: (7b) *(u64 *)(r10 -136) = r2\n; copylen = iovcnt * sizeof(struct iovec);\n345: (67) r2 <<= 4\n346: (bf) r1 = r2\n347: (67) r1 <<= 32\n348: (77) r1 >>= 32\n349: (18) r3 = 0xffffffff\n; if (copylen > SCRATCH_SIZE_MAX)\n351: (25) if r1 > 0x3ffff goto pc+2786\n R0=inv(id=0) R1_w=inv(id=0,umax_value=262143,var_off=(0x0; 0xfffffff0),s32_max_value=2147483632,u32_max_value=-16) R2_w=inv(id=12,smax_value=9223372036854775792,umax_value=18446744073709551600,var_off=(0x0; 0xfffffffffffffff0),s32_max_value=2147483632,u32_max_value=-16) R3_w=inv4294967295 R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=0) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=mmmmmmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-112=ctx fp-120=map_value fp-128=mmmmmmmm fp-136_w=mmmmmmmm\n; \n352: (79) r1 = *(u64 *)(r10 -96)\n; copylen & SCRATCH_SIZE_MAX,\n353: (57) r2 &= 262128\n354: (7b) *(u64 *)(r10 -144) = r1\n; if (bpf_probe_read((void *)iov,\n355: (bf) r3 = r8\n356: (85) call bpf_probe_read#4\n R0=inv(id=0) R1_w=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R2_w=inv(id=0,umax_value=262128,var_off=(0x0; 0x3fff0)) R3_w=inv(id=13) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=13) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=mmmmmmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-112=ctx fp-120=map_value fp-128=mmmmmmmm fp-136_w=mmmmmmmm fp-144_w=map_value\n R0=inv(id=0) R1_w=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R2_w=inv(id=0,umax_value=262128,var_off=(0x0; 0x3fff0)) R3_w=inv(id=13) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=13) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=mmmmmmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-112=ctx fp-120=map_value fp-128=mmmmmmmm fp-136_w=mmmmmmmm fp-144_w=map_value\nlast_idx 356 first_idx 343\nregs=4 stack=0 before 355: (bf) r3 = r8\nregs=4 stack=0 before 354: (7b) *(u64 *)(r10 -144) = r1\nregs=4 stack=0 before 353: (57) r2 &= 262128\nregs=4 stack=0 before 352: (79) r1 = *(u64 *)(r10 -96)\nregs=4 stack=0 before 351: (25) if r1 > 0x3ffff goto pc+2786\nregs=4 stack=0 before 349: (18) r3 = 0xffffffff\nregs=4 stack=0 before 348: (77) r1 >>= 32\nregs=4 stack=0 before 347: (67) r1 <<= 32\nregs=4 stack=0 before 346: (bf) r1 = r2\nregs=4 stack=0 before 345: (67) r2 <<= 4\nregs=4 stack=0 before 344: (7b) *(u64 *)(r10 -136) = r2\nregs=4 stack=0 before 343: (79) r2 = *(u64 *)(r10 -80)\n R0_w=inv(id=0) R6_w=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8_rw=inv(id=0) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80_rw=mmmmmmmm fp-88=map_value fp-96_r=map_value fp-104=map_value fp-112_w=ctx fp-120=map_value fp-128=mmmmmmmm\nparent already had regs=0 stack=0 marks\n357: (18) r3 = 0xfffffffe\n359: (67) r0 <<= 32\n360: (77) r0 >>= 32\n; if (bpf_probe_read((void *)iov,\n361: (55) if r0 != 0x0 goto pc+2776\n R0_w=inv0 R3_w=inv4294967294 R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=13) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=mmmmmmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-112=ctx fp-120=map_value fp-128=mmmmmmmm fp-136=mmmmmmmm fp-144=map_value\n362: (b7) r2 = 0\n; for (j = 0; j < MAX_IOVCNT; ++j) {\n363: (79) r1 = *(u64 *)(r10 -136)\n364: (15) if r1 == 0x0 goto pc+44\n R0_w=inv0 R1_w=inv(id=0) R2_w=inv0 R3_w=inv4294967294 R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=13) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=mmmmmmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-112=ctx fp-120=map_value fp-128=mmmmmmmm fp-136=mmmmmmmm fp-144=map_value\n365: (79) r5 = *(u64 *)(r10 -136)\n366: (07) r5 += -1\n367: (b7) r1 = 31\n368: (2d) if r1 > r5 goto pc+1\n R0=inv0 R1=inv31 R2=inv0 R3=inv4294967294 R5=inv(id=0,umin_value=31) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=13) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=mmmmmmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-112=ctx fp-120=map_value fp-128=mmmmmmmm fp-136=mmmmmmmm fp-144=map_value\n369: (b7) r5 = 31\n370: (b7) r3 = 0\n371: (bf) r4 = r5\n372: (07) r4 += 1\n373: (bf) r1 = r4\n374: (57) r1 &= 3\n375: (b7) r0 = 3\n376: (b7) r2 = 0\n377: (2d) if r0 > r5 goto pc+19\nlast_idx 377 first_idx 368\nregs=1 stack=0 before 376: (b7) r2 = 0\nregs=1 stack=0 before 375: (b7) r0 = 3\nlast_idx 377 first_idx 368\nregs=20 stack=0 before 376: (b7) r2 = 0\nregs=20 stack=0 before 375: (b7) r0 = 3\nregs=20 stack=0 before 374: (57) r1 &= 3\nregs=20 stack=0 before 373: (bf) r1 = r4\nregs=20 stack=0 before 372: (07) r4 += 1\nregs=20 stack=0 before 371: (bf) r4 = r5\nregs=20 stack=0 before 370: (b7) r3 = 0\nregs=20 stack=0 before 369: (b7) r5 = 31\n378: (b7) r0 = 0\n379: (79) r5 = *(u64 *)(r10 -96)\n380: (07) r5 += 40\n381: (bf) r3 = r4\n382: (57) r3 &= 60\n383: (57) r4 &= -4\n384: (87) r4 = -r4\n; size += iov[j].iov_len;\n385: (79) r2 = *(u64 *)(r5 -32)\n R0=inv0 R1=inv0 R2_w=inv0 R3=inv32 R4=inv(id=0) R5=map_value(id=0,off=40,ks=4,vs=262144,imm=0) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=13) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=mmmmmmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-112=ctx fp-120=map_value fp-128=mmmmmmmm fp-136=mmmmmmmm fp-144=map_value\n; size += iov[j].iov_len;\n386: (0f) r2 += r0\n; size += iov[j].iov_len;\n387: (79) r0 = *(u64 *)(r5 -16)\n R0_w=inv0 R1=inv0 R2_w=inv(id=0) R3=inv32 R4=inv(id=0) R5=map_value(id=0,off=40,ks=4,vs=262144,imm=0) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=13) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=mmmmmmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-112=ctx fp-120=map_value fp-128=mmmmmmmm fp-136=mmmmmmmm fp-144=map_value\n; size += iov[j].iov_len;\n388: (0f) r2 += r0\n; size += iov[j].iov_len;\n389: (79) r0 = *(u64 *)(r5 +0)\n R0_w=inv(id=0) R1=inv0 R2_w=inv(id=0) R3=inv32 R4=inv(id=0) R5=map_value(id=0,off=40,ks=4,vs=262144,imm=0) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=13) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=mmmmmmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-112=ctx fp-120=map_value fp-128=mmmmmmmm fp-136=mmmmmmmm fp-144=map_value\n; size += iov[j].iov_len;\n390: (0f) r2 += r0\n; size += iov[j].iov_len;\n391: (79) r0 = *(u64 *)(r5 +16)\n R0_w=inv(id=0) R1=inv0 R2_w=inv(id=0) R3=inv32 R4=inv(id=0) R5=map_value(id=0,off=40,ks=4,vs=262144,imm=0) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=13) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=mmmmmmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-112=ctx fp-120=map_value fp-128=mmmmmmmm fp-136=mmmmmmmm fp-144=map_value\n; size += iov[j].iov_len;\n392: (0f) r2 += r0\n; for (j = 0; j < MAX_IOVCNT; ++j) {\n393: (07) r5 += 64\n394: (07) r4 += 4\n395: (bf) r0 = r2\n396: (55) if r4 != 0x0 goto pc-12\n R0_w=inv(id=16) R1=inv0 R2_w=inv(id=16) R3=inv32 R4_w=inv0 R5_w=map_value(id=0,off=104,ks=4,vs=262144,imm=0) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=13) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=mmmmmmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-112=ctx fp-120=map_value fp-128=mmmmmmmm fp-136=mmmmmmmm fp-144=map_value\n397: (15) if r1 == 0x0 goto pc+11\nlast_idx 397 first_idx 385\nregs=2 stack=0 before 396: (55) if r4 != 0x0 goto pc-12\nregs=2 stack=0 before 395: (bf) r0 = r2\nregs=2 stack=0 before 394: (07) r4 += 4\nregs=2 stack=0 before 393: (07) r5 += 64\nregs=2 stack=0 before 392: (0f) r2 += r0\nregs=2 stack=0 before 391: (79) r0 = *(u64 *)(r5 +16)\nregs=2 stack=0 before 390: (0f) r2 += r0\nregs=2 stack=0 before 389: (79) r0 = *(u64 *)(r5 +0)\nregs=2 stack=0 before 388: (0f) r2 += r0\nregs=2 stack=0 before 387: (79) r0 = *(u64 *)(r5 -16)\nregs=2 stack=0 before 386: (0f) r2 += r0\nregs=2 stack=0 before 385: (79) r2 = *(u64 *)(r5 -32)\n R0_rw=inv0 R1_rw=invP0 R2_w=inv0 R3_w=inv32 R4_rw=inv(id=0) R5_rw=map_value(id=0,off=40,ks=4,vs=262144,imm=0) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=13) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=mmmmmmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-112=ctx fp-120=map_value fp-128=mmmmmmmm fp-136=mmmmmmmm fp-144=map_value\nparent didn't have regs=2 stack=0 marks\nlast_idx 384 first_idx 368\nregs=2 stack=0 before 384: (87) r4 = -r4\nregs=2 stack=0 before 383: (57) r4 &= -4\nregs=2 stack=0 before 382: (57) r3 &= 60\nregs=2 stack=0 before 381: (bf) r3 = r4\nregs=2 stack=0 before 380: (07) r5 += 40\nregs=2 stack=0 before 379: (79) r5 = *(u64 *)(r10 -96)\nregs=2 stack=0 before 378: (b7) r0 = 0\nregs=2 stack=0 before 377: (2d) if r0 > r5 goto pc+19\nregs=2 stack=0 before 376: (b7) r2 = 0\nregs=2 stack=0 before 375: (b7) r0 = 3\nregs=2 stack=0 before 374: (57) r1 &= 3\nregs=2 stack=0 before 373: (bf) r1 = r4\nregs=10 stack=0 before 372: (07) r4 += 1\nregs=10 stack=0 before 371: (bf) r4 = r5\nregs=20 stack=0 before 370: (b7) r3 = 0\nregs=20 stack=0 before 369: (b7) r5 = 31\n; for (j = 0; j < MAX_IOVCNT; ++j) {\n409: (79) r0 = *(u64 *)(r10 -120)\n; if (data->state->tail_ctx.curoff > SCRATCH_SIZE_HALF)\n410: (71) r1 = *(u8 *)(r0 +1)\n R0_w=map_value(id=0,off=20,ks=4,vs=77,imm=0) R1_w=invP0 R2=inv(id=16) R3=inv32 R4=inv0 R5=map_value(id=0,off=104,ks=4,vs=262144,imm=0) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=13) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=mmmmmmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-112=ctx fp-120=map_value fp-128=mmmmmmmm fp-136=mmmmmmmm fp-144=map_value\n411: (67) r1 <<= 8\n412: (71) r3 = *(u8 *)(r0 +0)\n R0_w=map_value(id=0,off=20,ks=4,vs=77,imm=0) R1_w=inv(id=0,umax_value=65280,var_off=(0x0; 0xff00)) R2=inv(id=16) R3_w=inv32 R4=inv0 R5=map_value(id=0,off=104,ks=4,vs=262144,imm=0) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=13) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=mmmmmmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-112=ctx fp-120=map_value fp-128=mmmmmmmm fp-136=mmmmmmmm fp-144=map_value\n413: (4f) r1 |= r3\n414: (71) r3 = *(u8 *)(r0 +3)\n R0_w=map_value(id=0,off=20,ks=4,vs=77,imm=0) R1_w=inv(id=0) R2=inv(id=16) R3_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R4=inv0 R5=map_value(id=0,off=104,ks=4,vs=262144,imm=0) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=13) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=mmmmmmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-112=ctx fp-120=map_value fp-128=mmmmmmmm fp-136=mmmmmmmm fp-144=map_value\n415: (67) r3 <<= 8\n416: (71) r4 = *(u8 *)(r0 +2)\n R0_w=map_value(id=0,off=20,ks=4,vs=77,imm=0) R1_w=inv(id=0) R2=inv(id=16) R3_w=inv(id=0,umax_value=65280,var_off=(0x0; 0xff00)) R4_w=inv0 R5=map_value(id=0,off=104,ks=4,vs=262144,imm=0) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=13) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=mmmmmmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-112=ctx fp-120=map_value fp-128=mmmmmmmm fp-136=mmmmmmmm fp-144=map_value\n417: (4f) r3 |= r4\n418: (67) r3 <<= 16\n419: (4f) r3 |= r1\n420: (71) r4 = *(u8 *)(r0 +5)\n R0_w=map_value(id=0,off=20,ks=4,vs=77,imm=0) R1_w=inv(id=0) R2=inv(id=16) R3_w=inv(id=0) R4_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R5=map_value(id=0,off=104,ks=4,vs=262144,imm=0) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=13) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=mmmmmmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-112=ctx fp-120=map_value fp-128=mmmmmmmm fp-136=mmmmmmmm fp-144=map_value\n421: (67) r4 <<= 8\n422: (71) r1 = *(u8 *)(r0 +4)\n R0_w=map_value(id=0,off=20,ks=4,vs=77,imm=0) R1_w=inv(id=0) R2=inv(id=16) R3_w=inv(id=0) R4_w=inv(id=0,umax_value=65280,var_off=(0x0; 0xff00)) R5=map_value(id=0,off=104,ks=4,vs=262144,imm=0) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=13) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=mmmmmmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-112=ctx fp-120=map_value fp-128=mmmmmmmm fp-136=mmmmmmmm fp-144=map_value\n423: (4f) r4 |= r1\n424: (71) r5 = *(u8 *)(r0 +6)\n R0_w=map_value(id=0,off=20,ks=4,vs=77,imm=0) R1_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R2=inv(id=16) R3_w=inv(id=0) R4_w=inv(id=0) R5_w=map_value(id=0,off=104,ks=4,vs=262144,imm=0) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=13) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=mmmmmmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-112=ctx fp-120=map_value fp-128=mmmmmmmm fp-136=mmmmmmmm fp-144=map_value\n425: (71) r1 = *(u8 *)(r0 +7)\n R0_w=map_value(id=0,off=20,ks=4,vs=77,imm=0) R1_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R2=inv(id=16) R3_w=inv(id=0) R4_w=inv(id=0) R5_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=13) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=mmmmmmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-112=ctx fp-120=map_value fp-128=mmmmmmmm fp-136=mmmmmmmm fp-144=map_value\n426: (67) r1 <<= 8\n427: (4f) r1 |= r5\n428: (67) r1 <<= 16\n429: (4f) r1 |= r4\n430: (67) r1 <<= 32\n431: (4f) r1 |= r3\n432: (79) r3 = *(u64 *)(r10 -128)\n; if ((flags & PRB_FLAG_IS_WRITE) == 0)\n433: (6d) if r2 s> r3 goto pc+1\n R0_w=map_value(id=0,off=20,ks=4,vs=77,imm=0) R1_w=inv(id=0) R2=inv(id=16) R3_w=inv(id=0) R4_w=inv(id=0) R5_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=13) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=mmmmmmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-112=ctx fp-120=map_value fp-128=mmmmmmmm fp-136=mmmmmmmm fp-144=map_value\n434: (bf) r3 = r2\n435: (7b) *(u64 *)(r10 -128) = r3\n436: (18) r3 = 0xffffffff\n; if (data->state->tail_ctx.curoff > SCRATCH_SIZE_HALF)\n438: (25) if r1 > 0x1ffff goto pc+2699\n R0_w=map_value(id=0,off=20,ks=4,vs=77,imm=0) R1_w=inv(id=0,umax_value=131071,var_off=(0x0; 0xffffffff)) R2=inv(id=16) R3_w=inv4294967295 R4_w=inv(id=0) R5_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=13) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=mmmmmmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-112=ctx fp-120=map_value fp-128_w=mmmmmmmm fp-136=mmmmmmmm fp-144=map_value\n; *((u32 *)&data->buf[data->state->tail_ctx.curoff & SCRATCH_SIZE_HALF]) = val;\n439: (bf) r2 = r9\n440: (0f) r2 += r1\nlast_idx 440 first_idx 409\nregs=2 stack=0 before 439: (bf) r2 = r9\nregs=2 stack=0 before 438: (25) if r1 > 0x1ffff goto pc+2699\nregs=2 stack=0 before 436: (18) r3 = 0xffffffff\nregs=2 stack=0 before 435: (7b) *(u64 *)(r10 -128) = r3\nregs=2 stack=0 before 434: (bf) r3 = r2\nregs=2 stack=0 before 433: (6d) if r2 s> r3 goto pc+1\nregs=2 stack=0 before 432: (79) r3 = *(u64 *)(r10 -128)\nregs=2 stack=0 before 431: (4f) r1 |= r3\nregs=a stack=0 before 430: (67) r1 <<= 32\nregs=a stack=0 before 429: (4f) r1 |= r4\nregs=1a stack=0 before 428: (67) r1 <<= 16\nregs=1a stack=0 before 427: (4f) r1 |= r5\nregs=3a stack=0 before 426: (67) r1 <<= 8\nregs=3a stack=0 before 425: (71) r1 = *(u8 *)(r0 +7)\nregs=38 stack=0 before 424: (71) r5 = *(u8 *)(r0 +6)\nregs=18 stack=0 before 423: (4f) r4 |= r1\nregs=1a stack=0 before 422: (71) r1 = *(u8 *)(r0 +4)\nregs=18 stack=0 before 421: (67) r4 <<= 8\nregs=18 stack=0 before 420: (71) r4 = *(u8 *)(r0 +5)\nregs=8 stack=0 before 419: (4f) r3 |= r1\nregs=a stack=0 before 418: (67) r3 <<= 16\nregs=a stack=0 before 417: (4f) r3 |= r4\nregs=1a stack=0 before 416: (71) r4 = *(u8 *)(r0 +2)\nregs=a stack=0 before 415: (67) r3 <<= 8\nregs=a stack=0 before 414: (71) r3 = *(u8 *)(r0 +3)\nregs=2 stack=0 before 413: (4f) r1 |= r3\nregs=a stack=0 before 412: (71) r3 = *(u8 *)(r0 +0)\nregs=2 stack=0 before 411: (67) r1 <<= 8\nregs=2 stack=0 before 410: (71) r1 = *(u8 *)(r0 +1)\n; *((u32 *)&data->buf[data->state->tail_ctx.curoff & SCRATCH_SIZE_HALF]) = val;\n441: (79) r3 = *(u64 *)(r10 -128)\n442: (63) *(u32 *)(r2 +0) = r3\n R0_w=map_value(id=0,off=20,ks=4,vs=77,imm=0) R1_w=invP(id=0,umax_value=131071,var_off=(0x0; 0xffffffff)) R2_w=map_value(id=0,off=0,ks=4,vs=262144,umax_value=131071,var_off=(0x0; 0xffffffff)) R3_w=inv(id=0) R4_w=inv(id=0) R5_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=13) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=mmmmmmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-112=ctx fp-120=map_value fp-128_w=mmmmmmmm fp-136=mmmmmmmm fp-144=map_value\n; fixup_evt_arg_len(data->buf, data->state->tail_ctx.curarg, len_dyn + len);\n443: (71) r2 = *(u8 *)(r7 +13)\n R0_w=map_value(id=0,off=20,ks=4,vs=77,imm=0) R1_w=invP(id=0,umax_value=131071,var_off=(0x0; 0xffffffff)) R2_w=map_value(id=0,off=0,ks=4,vs=262144,umax_value=131071,var_off=(0x0; 0xffffffff)) R3_w=inv(id=0) R4_w=inv(id=0) R5_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=13) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=mmmmmmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-112=ctx fp-120=map_value fp-128_w=mmmmmmmm fp-136=mmmmmmmm fp-144=map_value\n444: (67) r2 <<= 8\n445: (71) r3 = *(u8 *)(r7 +12)\n R0_w=map_value(id=0,off=20,ks=4,vs=77,imm=0) R1_w=invP(id=0,umax_value=131071,var_off=(0x0; 0xffffffff)) R2_w=inv(id=0,umax_value=65280,var_off=(0x0; 0xff00)) R3_w=inv(id=0) R4_w=inv(id=0) R5_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=13) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=mmmmmmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-112=ctx fp-120=map_value fp-128_w=mmmmmmmm fp-136=mmmmmmmm fp-144=map_value\n446: (4f) r2 |= r3\n447: (71) r3 = *(u8 *)(r7 +15)\n R0_w=map_value(id=0,off=20,ks=4,vs=77,imm=0) R1_w=invP(id=0,umax_value=131071,var_off=(0x0; 0xffffffff)) R2_w=inv(id=0) R3_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R4_w=inv(id=0) R5_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=13) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=mmmmmmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-112=ctx fp-120=map_value fp-128_w=mmmmmmmm fp-136=mmmmmmmm fp-144=map_value\n448: (67) r3 <<= 8\n449: (71) r4 = *(u8 *)(r7 +14)\n R0_w=map_value(id=0,off=20,ks=4,vs=77,imm=0) R1_w=invP(id=0,umax_value=131071,var_off=(0x0; 0xffffffff)) R2_w=inv(id=0) R3_w=inv(id=0,umax_value=65280,var_off=(0x0; 0xff00)) R4_w=inv(id=0) R5_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=13) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=mmmmmmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-112=ctx fp-120=map_value fp-128_w=mmmmmmmm fp-136=mmmmmmmm fp-144=map_value\n450: (4f) r3 |= r4\n451: (67) r3 <<= 16\n452: (4f) r3 |= r2\n453: (71) r4 = *(u8 *)(r7 +17)\n R0_w=map_value(id=0,off=20,ks=4,vs=77,imm=0) R1_w=invP(id=0,umax_value=131071,var_off=(0x0; 0xffffffff)) R2_w=inv(id=0) R3_w=inv(id=0) R4_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R5_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=13) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=mmmmmmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-112=ctx fp-120=map_value fp-128_w=mmmmmmmm fp-136=mmmmmmmm fp-144=map_value\n454: (67) r4 <<= 8\n455: (71) r2 = *(u8 *)(r7 +16)\n R0_w=map_value(id=0,off=20,ks=4,vs=77,imm=0) R1_w=invP(id=0,umax_value=131071,var_off=(0x0; 0xffffffff)) R2_w=inv(id=0) R3_w=inv(id=0) R4_w=inv(id=0,umax_value=65280,var_off=(0x0; 0xff00)) R5_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=13) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=mmmmmmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-112=ctx fp-120=map_value fp-128_w=mmmmmmmm fp-136=mmmmmmmm fp-144=map_value\n456: (4f) r4 |= r2\n457: (71) r5 = *(u8 *)(r7 +18)\n R0_w=map_value(id=0,off=20,ks=4,vs=77,imm=0) R1_w=invP(id=0,umax_value=131071,var_off=(0x0; 0xffffffff)) R2_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R3_w=inv(id=0) R4_w=inv(id=0) R5_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=13) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=mmmmmmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-112=ctx fp-120=map_value fp-128_w=mmmmmmmm fp-136=mmmmmmmm fp-144=map_value\n458: (71) r2 = *(u8 *)(r7 +19)\n R0_w=map_value(id=0,off=20,ks=4,vs=77,imm=0) R1_w=invP(id=0,umax_value=131071,var_off=(0x0; 0xffffffff)) R2_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R3_w=inv(id=0) R4_w=inv(id=0) R5_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=13) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=mmmmmmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-112=ctx fp-120=map_value fp-128_w=mmmmmmmm fp-136=mmmmmmmm fp-144=map_value\n459: (67) r2 <<= 8\n460: (4f) r2 |= r5\n461: (67) r2 <<= 16\n462: (4f) r2 |= r4\n463: (67) r2 <<= 32\n464: (4f) r2 |= r3\n; fixup_evt_arg_len(data->buf, data->state->tail_ctx.curarg, len_dyn + len);\n465: (bf) r3 = r2\n466: (67) r3 <<= 32\n467: (77) r3 >>= 32\n; if (argnum > PPM_MAX_EVENT_PARAMS)\n468: (25) if r3 > 0x20 goto pc+8\n R0=map_value(id=0,off=20,ks=4,vs=77,imm=0) R1=invP(id=0,umax_value=131071,var_off=(0x0; 0xffffffff)) R2=inv(id=17) R3=inv(id=0,umax_value=32,var_off=(0x0; 0xffffffff)) R4=inv(id=0) R5=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=13) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=mmmmmmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-112=ctx fp-120=map_value fp-128=mmmmmmmm fp-136=mmmmmmmm fp-144=map_value\n; volatile unsigned int argnumv = argnum;\n469: (63) *(u32 *)(r10 -80) = r2\n; *((u16 *)&p[sizeof(struct ppm_evt_hdr)] + (argnumv & (PPM_MAX_EVENT_PARAMS - 1))) = arglen;\n470: (61) r3 = *(u32 *)(r10 -80)\n; *((u16 *)&p[sizeof(struct ppm_evt_hdr)] + (argnumv & (PPM_MAX_EVENT_PARAMS - 1))) = arglen;\n471: (57) r3 &= 31\n472: (67) r3 <<= 1\n; *((u16 *)&p[sizeof(struct ppm_evt_hdr)] + (argnumv & (PPM_MAX_EVENT_PARAMS - 1))) = arglen;\n473: (bf) r4 = r9\n474: (0f) r4 += r3\nlast_idx 474 first_idx 468\nregs=8 stack=0 before 473: (bf) r4 = r9\nregs=8 stack=0 before 472: (67) r3 <<= 1\nregs=8 stack=0 before 471: (57) r3 &= 31\nregs=8 stack=0 before 470: (61) r3 = *(u32 *)(r10 -80)\n475: (b7) r3 = 4\n; *((u16 *)&p[sizeof(struct ppm_evt_hdr)] + (argnumv & (PPM_MAX_EVENT_PARAMS - 1))) = arglen;\n476: (6b) *(u16 *)(r4 +26) = r3\n R0=map_value(id=0,off=20,ks=4,vs=77,imm=0) R1=invP(id=0,umax_value=131071,var_off=(0x0; 0xffffffff)) R2=inv(id=17) R3_w=inv4 R4_w=map_value(id=0,off=0,ks=4,vs=262144,umax_value=62,var_off=(0x0; 0x3e)) R5=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=13) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=mmmmmmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-112=ctx fp-120=map_value fp-128=mmmmmmmm fp-136=mmmmmmmm fp-144=map_value\n; data->state->tail_ctx.len += len;\n477: (71) r3 = *(u8 *)(r7 +29)\n R0=map_value(id=0,off=20,ks=4,vs=77,imm=0) R1=invP(id=0,umax_value=131071,var_off=(0x0; 0xffffffff)) R2=inv(id=17) R3_w=inv4 R4_w=map_value(id=0,off=0,ks=4,vs=262144,umax_value=62,var_off=(0x0; 0x3e)) R5=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=13) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=mmmmmmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-112=ctx fp-120=map_value fp-128=mmmmmmmm fp-136=mmmmmmmm fp-144=map_value\n478: (67) r3 <<= 8\n479: (71) r4 = *(u8 *)(r7 +28)\n R0=map_value(id=0,off=20,ks=4,vs=77,imm=0) R1=invP(id=0,umax_value=131071,var_off=(0x0; 0xffffffff)) R2=inv(id=17) R3_w=inv(id=0,umax_value=65280,var_off=(0x0; 0xff00)) R4_w=map_value(id=0,off=0,ks=4,vs=262144,umax_value=62,var_off=(0x0; 0x3e)) R5=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=13) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=mmmmmmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-112=ctx fp-120=map_value fp-128=mmmmmmmm fp-136=mmmmmmmm fp-144=map_value\n480: (4f) r3 |= r4\n481: (71) r4 = *(u8 *)(r7 +31)\n R0=map_value(id=0,off=20,ks=4,vs=77,imm=0) R1=invP(id=0,umax_value=131071,var_off=(0x0; 0xffffffff)) R2=inv(id=17) R3_w=inv(id=0) R4_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R5=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=13) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=mmmmmmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-112=ctx fp-120=map_value fp-128=mmmmmmmm fp-136=mmmmmmmm fp-144=map_value\n482: (67) r4 <<= 8\n483: (71) r5 = *(u8 *)(r7 +30)\n R0=map_value(id=0,off=20,ks=4,vs=77,imm=0) R1=invP(id=0,umax_value=131071,var_off=(0x0; 0xffffffff)) R2=inv(id=17) R3_w=inv(id=0) R4_w=inv(id=0,umax_value=65280,var_off=(0x0; 0xff00)) R5_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=13) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=mmmmmmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-112=ctx fp-120=map_value fp-128=mmmmmmmm fp-136=mmmmmmmm fp-144=map_value\n484: (4f) r4 |= r5\n485: (67) r4 <<= 16\n486: (4f) r4 |= r3\n487: (71) r5 = *(u8 *)(r7 +33)\n R0=map_value(id=0,off=20,ks=4,vs=77,imm=0) R1=invP(id=0,umax_value=131071,var_off=(0x0; 0xffffffff)) R2=inv(id=17) R3_w=inv(id=0) R4_w=inv(id=0) R5_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=13) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=mmmmmmmm fp-88=map_value fp-96=map_value fp-104=map_value fp-112=ctx fp-120=map_value fp-128=mmmmmmmm fp-136=mmmmmmmm fp-144=map_value\n488: (67) r5 <<= 8\n489: (71) r3 = *(u8 *)(r7 +32)\n R0=map_value(id=0,off=20,ks=4,vs=77,imm=0) R1=invP(id=0,umax_value=131071,var_off=(0x0; 0xffffffff)) R2=inv(id=17) R3_w=inv(id=0) R4_w=inv(id=0) R5_w=inv(id=0,umax_value=65280,var_off=(0x0; 0xff00)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=77,imm=0) R8=inv(id=13) R9=map_value(id=0,off=0,ks=4,vs=262144,imm=0) R10=fp0 fp-80=mmmmmmmm fp (truncated...)
```

</details>

**How to reproduce it**

- Install clang 12
- `cd driver/bpf && make`

**Expected behaviour**

- The verifier is happy

**Screenshots**

**Environment**

**Additional context**

### PR DESCRIPTION
**Pull request by FedeDP**
```
Signed-off-by: Federico Di Pierro <nierro92@gmail.com>
Co-authored-by: Jason Dellaluce <jasondellaluce@gmail.com>
```

**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area driver-ebpf

**What this PR does / why we need it**:

So far, the eBPF probe needs to be compiled with clang 7. Although newer versions of clang can successfully compile the probe, it then gets rejected by the kernel verifier. This has been an open issue for a while.

This PR applies a small set of fixes that allow our eBPF probe to be accepted by the kernel verifier even when compiled with recent versions of clang.  
So far, we tested this on various versions of the linux kernel and of clang.  
These are the results of our test grid, which we ran on amd64 architecture:

|  Kernel Ver.  | 5.14 | 5.11 | 5.8 | 5.4 | 4.19 | 4.17 | 4.15 |
|:------------:|:----:|:----:|:---:|:---:|:----:|:----:|:----:|
| **clang-7**  |  --  |  OK  | OK  | OK  |  OK  |  OK  | OK |
| **clang-8**  |  --  |  OK  | OK  | OK  |  OK  |  OK  | OK |
| **clang-9**  |  --  |  OK  | OK  | OK  |  OK  |  OK  | OK |
| **clang-10** |  --  |  OK  | OK  | OK  |  OK  |  OK  | OK |
| **clang-11** |  --  |  OK  | OK  | OK  |  OK  |  OK  | OK |
| **clang-12** |  OK  |  OK  | OK  | OK  |  OK  |  OK  | OK |
| **clang-14** |  --  |  OK  | OK  | OK  |  OK  |  OK  | **KO** |

### Additional context
At a high level, the kernel verifier rejects the eBPF for three main reasons:

1. **Unclear exit conditions in bounded loops**. In some cases where the exit condition of a unrolled loop is a little ambiguous, the verifier is not able to predict if some memory accesses can go out of bounds. An example is visible [here](https://github.com/falcosecurity/libs/pull/81/files#diff-a8b6fc07077f8fcef2f22e51392da619a5e68b7c603c62b3ab93ce5b6be22d6bR311). In this case, a check on the `off` variable is required because it is used to access memory inside `data->buf[off & ...]`. We solved the error by checking the value of `off` at the beginning of the loop.
2. **Unprotected memory accesses**. Accessing memory with patterns like `&buf[off & SCRATCH_SIZE_HALF]`, visible [here](https://github.com/falcosecurity/libs/pull/81/files#diff-a8b6fc07077f8fcef2f22e51392da619a5e68b7c603c62b3ab93ce5b6be22d6bR1514), is often rejected if compiled with newest clang versions. This is due to an optimization applied during the compilation. If a check such as `if (off > SCRATCH_SIZE_HALF) /* fail /*` appears before a memory access such as `&buf[off & SCRATCH_SIZE_HALF]`, the compiler avoids performing the `& SCRATCH_SIZE_HALF` operation by assuming that the value of `off` is already bounded because it is checked inside the if statement. However, the compiled eBPF bytecode gets then rejected by the kernel verifier because it has no way to predict the value of `off` when accessing the memory buffer. We fixed this by storing the result of `off & SCRATCH_SIZE_HALF` in an additional variable, so that the compiler is forced to perform the bitwise bounding operation.
3. **Passing long integers to eBPF helpers**. Helpers such as `bpf_probe_read`, accept a `size` argument that is defined as a `signed integer`. However, in multiple instances (such as [here](https://github.com/falcosecurity/libs/pull/81/files#diff-c8f0685e0b19ed879c6a46c5570ae4e960346c349f9e477f2127542d6daa6c85R769)) we pass `unsigned long` variables as `size` arguments. We assume the safety of this operation by checking that the value does not go beyond a certain threshold, or by bouding its value through a bitwise and operation, but this is not sufficient. The kernel verifier recognizes an attempt of converting an `u64` to a `s32`, and predicts the possibility of the value to become negative due to the potential bit overflow. We solved this problem by defining the passed value as `u16`, which was quite sufficient to cover our use cases (our max value fits in 16 bits comfortably).

**Which issue(s) this PR fixes**:
Fixes #58 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: driver/bpf/fillers.h [hunk 1]
```diff
@@ -415,10 +410,14 @@ static __always_inline int bpf_parse_readv_writev_bufs(struct filler_data *data,
 #endif
 		return PPM_FAILURE_INVALID_USER_MEMORY;
 
+
 	#pragma unroll
 	for (j = 0; j < MAX_IOVCNT; ++j) {
 		if (j == iovcnt)
 			break;
+		// BPF seems to require an hard limit to avoid overflows
```
Comment (zuc) [inline driver/bpf/fillers.h:418]:
```suggestion
		// BPF seems to require a hard limit to avoid overflows
```

Comment (FedeDP) [reply driver/bpf/fillers.h:418]: Thank you!

**Comment by lucklypse** [comment]
Does it finally fix this issue? https://github.com/falcosecurity/libs/issues/58

**Comment by FedeDP** [comment]
In my case, it fixed the issue. 
I think #58 is related as it talks about `bpf_sys_readv_preadv_x` that internally calls `bpf_parse_readv_writev_bufs`, that is one of the two fixed functions in this PR.

**Comment by FedeDP** [comment]
Sorry, i had to force push because we missed a Signed-off in the commit suggested by @zuc and committed via github.

File: driver/bpf/filler_helpers.h [hunk 2]
```diff
@@ -719,17 +719,20 @@ static __always_inline int __bpf_val_to_ring(struct filler_data *data,
 {
 	unsigned int len_dyn = 0;
 	unsigned int len;
+	unsigned long curoff_bounded;
 
+	curoff_bounded = data->state->tail_ctx.curoff & SCRATCH_SIZE_HALF;
 	if (data->state->tail_ctx.curoff > SCRATCH_SIZE_HALF)
 		return PPM_FAILURE_BUFFER_FULL;
-
+
```
Comment (leogr) [inline driver/bpf/filler_helpers.h:727]:
```suggestion

```

File: driver/bpf/filler_helpers.h [hunk 3]
```diff
@@ -871,7 +874,7 @@ static __always_inline int __bpf_val_to_ring(struct filler_data *data,
 		return PPM_FAILURE_BUG;
 	}
 	}
-
+
```
Comment (leogr) [inline driver/bpf/filler_helpers.h:877]:
```suggestion

```

**Review by leogr — COMMENTED** [review]
Just found two unneeded whitespaces (see suggestions below), otherwise looks awesome :star_struck: 

I reserve some time to test it before the definitive approval.

Thank you!

**Review by leogr — APPROVED** [review]
LGTM :partying_face: 
Btw, many thanks for the detailed explanation, and congrats: these fixes are excellent! :clap: 

/approve

**Review by ldegio — APPROVED** [review]
