### PR TITLE
fix(build): fix tests build warnings (fatal with -Werror)

### LINKED ISSUE #2052: Tons of build issues with missing field initializers
**Describe the bug**

When building with -Werror, I'm getting literally hundreds of errors related to missing designated field initializers:

```
.../test/drivers/test_suites/syscall_exit_suite/sendto_x.cpp:18:81: error: missing initializer for member ‘send_data::greater_snaplen’ [-Werror=missing-field-initializers]
   18 |         evt_test->client_to_server_ipv4_tcp(send_data{.syscall_num = __NR_sendto});
```

AFAIK partial initialization with designated initializers isn't valid C++ (which doesn't make any sense but here we are).

**How to reproduce it**

Hmm, just build with -DCMAKE_BUILD_WARNINGS_AS_ERRORS=On, I suppose.

**Expected behaviour**

I expected a successful build.

**Screenshots**

I'm not pasting all the errors here, it's literally hundreds and hundreds.

**Environment**

```
$ gcc --version
gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Additional context**

I'm hoping we can find some compiler-flag based solution (a gcc extension maybe), because otherwise we're looking at an insane number of patches like this one:

```
 	/*=============================== TRIGGER SYSCALL  ===========================*/
 
-	evt_test->client_to_server_ipv4_tcp(send_data{.syscall_num = __NR_sendto, .greater_snaplen = true},
-					    recv_data{.syscall_num = __NR_read});
+	evt_test->client_to_server_ipv4_tcp(
+	        send_data{.syscall_num = __NR_sendto, .greater_snaplen = true, .null_sockaddr = false},
+	        recv_data{.syscall_num = __NR_read,
+	                  .null_sockaddr = false,
+	                  .null_receiver_buffer = false,
+	                  .skip_recv_phase = false});

```

Switching to C++20 just causes *more* errors. Don't ask me why or how (this file is C, not C++) but then it also complains about https://github.com/falcosecurity/libs/blob/master/userspace/libscap/linux/scap_cgroup.c#L796 mixing designated and non-designated initializers (that one could just be `{}` I guess).

Also, am I the only one in the world building with -Werror or is my compiler sufficiently different from whatever is used in CI?

cc @Andreagit97 @federico-sysdig

### PR DESCRIPTION
**Pull request by gnosek**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area API-version

/area build

> /area CI

> /area driver-kmod

> /area driver-bpf

> /area driver-modern-bpf

> /area libscap-engine-bpf

> /area libscap-engine-gvisor

> /area libscap-engine-kmod

> /area libscap-engine-modern-bpf

> /area libscap-engine-nodriver

> /area libscap-engine-noop

> /area libscap-engine-source-plugin

> /area libscap-engine-savefile

> /area libscap

> /area libpman

> /area libsinsp

/area tests

> /area proposals

**Does this PR require a change in the driver versions?**

> /version driver-API-version-major

> /version driver-API-version-minor

> /version driver-API-version-patch

> /version driver-SCHEMA-version-major

> /version driver-SCHEMA-version-minor

> /version driver-SCHEMA-version-patch

**What this PR does / why we need it**:

Every time I run a build with -Werror, I run into new and exciting issues. This is another round of shaving yaks just so I can get my own stuff done, so I took the liberty of adding -Werror to the CI driver_test builds.

**Which issue(s) this PR fixes**:

Fixes #2052

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by gnosek** [comment]
cc @Andreagit97 @federico-sysdig

File: test/drivers/event_class/event_class.h [hunk 1]
```diff
@@ -39,15 +39,15 @@ struct fd_poll
...
 struct send_data {
 	int syscall_num;
-	bool greater_snaplen;
-	bool null_sockaddr;
+	bool greater_snaplen = false;
+	bool null_sockaddr = false;
 };
 
 struct recv_data {
 	int syscall_num;
```
Comment (Andreagit97) [inline test/drivers/event_class/event_class.h:47]: Why don't we initialize this to `0` as well?

File: .github/workflows/drivers_ci.yml [hunk 2]
```diff
@@ -85,7 +85,7 @@ jobs:
         if: needs.paths-filter.outputs.driver == 'true' || needs.paths-filter.outputs.libscap == 'true' || needs.paths-filter.outputs.libpman == 'true'
         run: |
           mkdir -p build
-          cd build && cmake -DUSE_BUNDLED_DEPS=On -DBUILD_DRIVER=ON -DBUILD_LIBSCAP_MODERN_BPF=ON -DBUILD_BPF=On -DBUILD_LIBSCAP_GVISOR=${{ matrix.enable_gvisor }} -DCREATE_TEST_TARGETS=On -DENABLE_LIBSCAP_TESTS=On ../
+          cd build && cmake -DBUILD_WARNINGS_AS_ERRORS=On -DUSE_BUNDLED_DEPS=On -DBUILD_DRIVER=ON -DBUILD_LIBSCAP_MODERN_BPF=ON -DBUILD_BPF=On -DBUILD_LIBSCAP_GVISOR=${{ matrix.enable_gvisor }} -DCREATE_TEST_TARGETS=On -DENABLE_LIBSCAP_TESTS=On ../
```
Comment (Andreagit97) [inline .github/workflows/drivers_ci.yml:88]: since the CI is green I don't see any issue in enabling it from now! WDYT @FedeDP?

**Comment by Andreagit97** [comment]
Thank you very much for the fixes! I think we will need a rebase after this https://github.com/falcosecurity/libs/pull/2051 but i can take care of it if it's ok for you!

File: .github/workflows/drivers_ci.yml (hunk 2 above)
Comment (FedeDP) [reply .github/workflows/drivers_ci.yml:88]: Yep! +1!

File: test/drivers/event_class/event_class.h (hunk 1 above)
Comment (gnosek) [reply test/drivers/event_class/event_class.h:47]: This feels like a field that doesn't have a reasonable default (0 will raise an error when reached) so I left it to be explicitly initialized.

**Comment by gnosek** [comment]
> Thank you very much for the fixes! I think we will need a rebase after this #2051 but i can take care of it if it's ok for you!

Whatever works for you :) I can rebase and clang-format no problem, but I will haunt you if that doesn't make the CI pass ;P

File: test/drivers/test_suites/syscall_exit_suite/execveat_x.cpp [hunk 3]
```diff
@@ -213,6 +213,7 @@ TEST(SyscallExit, execveatX_correct_exit)
 	const char *newargv[] = {pathname, "", "first_argv", "", too_long_arg.c_str(), "second_argv", NULL};
 	const char *newenviron[] = {"IN_TEST=yes", "3_ARGUMENT=yes", too_long_arg.c_str(), "2_ARGUMENT=no", NULL};
 
+#if defined(__s390x__) || defined(__riscv) || defined(__powerpc64__) || defined(__loongarch64)
```
Comment (FedeDP) [inline test/drivers/test_suites/syscall_exit_suite/execveat_x.cpp:216]: Out of curiosity, why was this fix needed?

Comment (FedeDP) [reply test/drivers/test_suites/syscall_exit_suite/execveat_x.cpp:216]: Oh i see now, larger context helped eheh
unused variable warning i guess.

File: test/drivers/event_class/event_class.h (hunk 1 above)
Comment (Andreagit97) [reply test/drivers/event_class/event_class.h:47]: it was just to avoid specifying it manually to `0` when we use `skip_recv_phase=true`. if `skip_recv_phase==true` no recv syscall will be called so it could be ok to have it to `0`, but i get your point

**Comment by FedeDP** [comment]
@gnosek can you rebase? Please make sure to follow https://github.com/falcosecurity/libs/blob/master/Contributing.md#enforce-coding-style- to properly auto-format the code.

**Comment by Andreagit97** [comment]
i will do it!

File: test/drivers/event_class/event_class.h (hunk 1 above)
Comment (Andreagit97) [reply test/drivers/event_class/event_class.h:44]: we can do it in a follow up

**Comment by Andreagit97** [comment]
Done

**Review by Andreagit97 — APPROVED** [review]
/approve

**Review by FedeDP — APPROVED** [review]
/approve
