### PR TITLE
fix(driver/bpf): fixed a couple of verifier issues.

### LINKED ISSUE #1890: Serious eBPF driver regression starting with 0.16.x libs
When I last forked off usptream (libs 0.15.x) the eBPF driver (legacy and modern_ebpf) continued to work wonderfully as they did did for almost 1.5 years. 

However, now there seem to be serious issues and regressions for older kernels, but I have also observed issues with modern_ebpf depending on the compiler version used.

I tried clang 12, 14, 16, 18 with some updated builder containers. While the eBPF probes compiled I have either observed eBPF verifier issues (one time for sys_poll, another time for sys_preadv). I also observed scap errors during initialization or map type not allowed errors ... in summary, it does not appear to be very clear what the issue is, especially because there were a lot of changes.

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area driver-bpf

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

https://github.com/falcosecurity/libs/pull/1814 and https://github.com/falcosecurity/libs/pull/1767 introduced 2 old bpf verifier regressions.
This PR aims at fixing them.

**Which issue(s) this PR fixes**:

Fixes #1890 

**Special notes for your reviewer**:

Already tested against our kernel matrix (https://github.com/falcosecurity/libs/actions/runs/9386047428):
AMD64:
|        KERNEL        | CMAKE-CONFIGURE | KMOD BUILD | KMOD SCAP-OPEN |            BPF-PROBE BUILD             |            BPF-PROBE SCAP-OPEN             |             MODERN-BPF SCAP-OPEN             |
|----------------------|-----------------|------------|----------------|----------------------------------------|--------------------------------------------|----------------------------------------------|
| amazonlinux2-4.19    | 🟢              | 🟢         | 🟢             | 🟢                                     | 🟢                                         | [🟡](#amazonlinux2-419-modern-bpf_scap-open) |
| amazonlinux2-5.10    | 🟢              | 🟢         | 🟢             | 🟢                                     | 🟢                                         | 🟢                                           |
| amazonlinux2-5.15    | 🟢              | 🟢         | 🟢             | 🟢                                     | 🟢                                         | 🟢                                           |
| amazonlinux2-5.4     | 🟢              | 🟢         | 🟢             | 🟢                                     | 🟢                                         | [🟡](#amazonlinux2-54-modern-bpf_scap-open)  |
| amazonlinux2022-5.15 | 🟢              | 🟢         | 🟢             | 🟢                                     | 🟢                                         | 🟢                                           |
| amazonlinux2023-6.1  | 🟢              | 🟢         | 🟢             | 🟢                                     | 🟢                                         | 🟢                                           |
| archlinux-6.0        | 🟢              | 🟢         | 🟢             | 🟢                                     | 🟢                                         | 🟢                                           |
| archlinux-6.7        | 🟢              | 🟢         | 🟢             | 🟢                                     | 🟢                                         | 🟢                                           |
| centos-3.10          | 🟢              | 🟢         | 🟢             | [🟡](#centos-310-bpf-probe_build)      | [🟡](#centos-310-bpf-probe_scap-open)      | [🟡](#centos-310-modern-bpf_scap-open)       |
| centos-4.18          | 🟢              | 🟢         | 🟢             | 🟢                                     | 🟢                                         | 🟢                                           |
| centos-5.14          | 🟢              | 🟢         | 🟢             | 🟢                                     | 🟢                                         | 🟢                                           |
| fedora-5.17          | 🟢              | 🟢         | 🟢             | 🟢                                     | 🟢                                         | 🟢                                           |
| fedora-5.8           | 🟢              | 🟢         | 🟢             | 🟢                                     | 🟢                                         | 🟢                                           |
| fedora-6.2           | 🟢              | 🟢         | 🟢             | 🟢                                     | 🟢                                         | 🟢                                           |
| oraclelinux-3.10     | 🟢              | 🟢         | 🟢             | [🟡](#oraclelinux-310-bpf-probe_build) | [🟡](#oraclelinux-310-bpf-probe_scap-open) | [🟡](#oraclelinux-310-modern-bpf_scap-open)  |
| oraclelinux-4.14     | 🟢              | 🟢         | 🟢             | 🟢                                     | 🟢                                         | [🟡](#oraclelinux-414-modern-bpf_scap-open)  |
| oraclelinux-5.15     | 🟢              | 🟢         | 🟢             | 🟢                                     | 🟢                                         | 🟢                                           |
| oraclelinux-5.4      | 🟢              | 🟢         | 🟢             | 🟢                                     | 🟢                                         | [🟡](#oraclelinux-54-modern-bpf_scap-open)   |
| ubuntu-4.15          | 🟢              | 🟢         | 🟢             | 🟢                                     | 🟢                                         | [🟡](#ubuntu-415-modern-bpf_scap-open)       |
| ubuntu-5.8           | 🟢              | 🟢         | 🟢             | 🟢                                     | 🟢                                         | [🟡](#ubuntu-58-modern-bpf_scap-open)        |
| ubuntu-6.5           | 🟢              | 🟢         | 🟢             | 🟢                                     | 🟢                                         | 🟢                                           |

arm64:
|        KERNEL        | CMAKE-CONFIGURE | KMOD BUILD | KMOD SCAP-OPEN |            BPF-PROBE BUILD             |            BPF-PROBE SCAP-OPEN             |            MODERN-BPF SCAP-OPEN             |
|----------------------|-----------------|------------|----------------|----------------------------------------|--------------------------------------------|---------------------------------------------|
| amazonlinux2-5.4     | 🟢              | 🟢         | 🟢             | 🟢                                     | 🟢                                         | [🟡](#amazonlinux2-54-modern-bpf_scap-open) |
| amazonlinux2022-5.15 | 🟢              | 🟢         | 🟢             | 🟢                                     | 🟢                                         | 🟢                                          |
| fedora-6.2           | 🟢              | 🟢         | 🟢             | 🟢                                     | 🟢                                         | 🟢                                          |
| oraclelinux-4.14     | 🟢              | 🟢         | 🟢             | [🟡](#oraclelinux-414-bpf-probe_build) | [🟡](#oraclelinux-414-bpf-probe_scap-open) | [🟡](#oraclelinux-414-modern-bpf_scap-open) |
| oraclelinux-5.15     | 🟢              | 🟢         | 🟢             | 🟢                                     | 🟢                                         | 🟢                                          |
| ubuntu-6.5           | 🟢              | 🟢         | 🟢             | 🟢                                     | 🟢                                         | 🟢                                          |

**Does this PR introduce a user-facing change?**:

```release-note
fix(driver/bpf): fixed a couple of verifier issues.
```

/milestone next-driver
/cc @incertum @Andreagit97

### CODE REVIEW

File: driver/bpf/fillers.h [hunk 1]
```diff
@@ -571,236 +571,158 @@ FILLER(sys_poll_x, true)
 	return bpf_poll_parse_fds(data, false);
 }
 
-#define MAX_IOVCNT 32
-#define MAX_IOVCNT_COMPAT 8
+#ifdef CONFIG_COMPAT
```
Comment (FedeDP) [inline driver/bpf/fillers.h:574]: Only real downside of the patch (except for its ugliness probably :D ) is that we will have max iovec count of 8 when config compat is enabled; this is needed because we must have a constant to be able to unroll the loops below. Not a big deal; this is only on the old ebpf probe.

File: driver/bpf/fillers.h [hunk 2]
```diff
@@ -571,236 +571,158 @@ FILLER(sys_poll_x, true)
...
+		if (size == LONG_MAX)
 			break;
 
-		*size += iov[j].iov_len;
+		volatile unsigned curr_shift = j * iov_size + len_off;
+		unsigned long shift_bounded = curr_shift & SCRATCH_SIZE_HALF;
+		if (curr_shift > SCRATCH_SIZE_HALF)
+			break;
+
+		long curr_len;
```
Comment (FedeDP) [inline driver/bpf/fillers.h:637]: Don't know why, it won't make me use `memcpy` (that is an alias for `__builtin_memcpy` from clang) here.

Comment (FedeDP) [reply driver/bpf/fillers.h:637]: If i could use `memcpy` the patch would look much tidier, but that's not the case unfortunately.

File: driver/bpf/fillers.h [hunk 3]
```diff
@@ -4312,10 +4234,12 @@ FILLER(sys_recvfrom_x, true)
 	unsigned long val;
 	uint16_t size = 0;
 	long retval;
-	int addrlen;
+	int addrlen = 0;
```
Comment (FedeDP) [inline driver/bpf/fillers.h:4237]: `recvfrom` instead looks tidier now imo.

File: driver/bpf/fillers.h [hunk 4]
```diff
@@ -571,236 +571,158 @@ FILLER(sys_poll_x, true)
...
-#define MAX_IOVCNT 32
-#define MAX_IOVCNT_COMPAT 8
+#ifdef CONFIG_COMPAT
+	#define MAX_IOVCNT 8
+#else
+	#define MAX_IOVCNT 32
+#endif
 
-static __always_inline int bpf_parse_readv_writev_bufs_64(struct filler_data *data,
+static __always_inline int bpf_parse_readv_writev_bufs(struct filler_data *data,
```
Comment (Andreagit97) [inline driver/bpf/fillers.h:580]: to be honest I would prefer to revert this code to what we had before this PR https://github.com/falcosecurity/libs/pull/1814/files#diff-a8b6fc07077f8fcef2f22e51392da619a5e68b7c603c62b3ab93ce5b6be22d6b. The new implementation seems pretty easy to break and the only advantage is that we support `readv` and `writev` on 32 bits... that IMO is a corner case.

Btw if you feel confident we can also merge it and maybe revert it if we see it doesn't work well...

**Comment by incertum** [comment]
:rocket: posted current results here https://github.com/falcosecurity/libs/issues/1890#issuecomment-2150595720

File: driver/bpf/fillers.h (hunk 4 above)
Comment (FedeDP) [reply driver/bpf/fillers.h:580]: Yep, i would love to be able to just use `memcpy` there (the clang builtin of course); but it won't work :/ it would make the code much better...

File: driver/bpf/fillers.h (hunk 2 above)
Comment (FedeDP) [reply driver/bpf/fillers.h:637]: Oh we can't because for `__builtin_memcpy` size must be a compile time constant.

**Comment by FedeDP** [comment]
@incertum this is now ready IMO. Other regressions you highlighted (mostly referring to https://github.com/falcosecurity/libs/issues/1890#issuecomment-2150769343) are not verifier issues, thus we can go on with this.

I'd like to understand them too though, we can digging into that on #1890 ; feel free to add any new info you got :)

**Comment by incertum** [comment]
> @incertum this is now ready IMO. Other regressions you highlighted (mostly referring to [#1890 (comment)](https://github.com/falcosecurity/libs/issues/1890#issuecomment-2150769343)) are not verifier issues, thus we can go on with this.
> 
> I'd like to understand them too though, we can digging into that on #1890 ; feel free to add any new info you got :)

Agree, we will dig into this separately.

**Review by incertum — APPROVED** [review]
/approve

Nice job @FedeDP and also thanks!

**Review by Andreagit97 — APPROVED** [review]
/approve
