### PR TITLE
fix(gvisor): handle arbitrary sandbox IDs

### LINKED ISSUE #1602: gVisor engine crashes with non-hex container IDs
**Describe the bug**

This issue comes from the analysis in: https://github.com/falcosecurity/falco/issues/2897 . Currently, the gVisor engine crashes if a non-hex container ID is used.

**How to reproduce it**

Example:
```bash
# create a container bundle
mkdir redis
mkdir redis/rootfs
docker pull redis
docker create --name tempredis redis
docker export tempredis | tar -C redis/rootfs -xf -
docker rm tempredis
cd ./redis/
runc spec
cd ..
# run a runsc sandbox with a non-hex id
sudo runsc -platform=systrap -file-access=shared -host-uds=open -overlay2=none -directfs -dcache=0 --cpu-num-from-quota --pod-init-config=/etc/docker/runsc_falco_config.json -debug-log=/tmp/runsc/ -debug -strace run -bundle redis/ my_container_id
```

Meanwhile, run Falco with gVisor integration enabled.

**Expected behaviour**

**Screenshots**

**Environment**

libs 0.14.0

**Additional context**

### PR DESCRIPTION
**Pull request by LucaGuerra**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area libscap-engine-gvisor

**Does this PR require a change in the driver versions?**

No.

**What this PR does / why we need it**:

In the gvisor engine we handle the sandbox ID by generating a numeric value to represent it and using it in the pid/tid fields to distinguish between containers. This was initially extracted from the string itself if it was written in hex (like it is normally in containerd, docker, ...) but it is not a reliable way because it does not handle arbitrary strings or collisions.

This PR fixes it by implementing the following:
- A function in the platform that generates unique ID for each active sandbox, maintaining a 1:1 mapping with the string ID
- A function in the parsers that can extract the container ID as a string
- State tracking in the gvisor engine to associate numeric IDs to sandbox fds

**Which issue(s) this PR fixes**:

Fixes #1602

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fix(gvisor): handle arbitrary sandbox IDs
```

### CODE REVIEW

File: userspace/libscap/engine/gvisor/gvisor_public.h [hunk 1]
```diff
@@ -30,6 +30,7 @@ extern "C"
 
 		bool no_events; //< Pinky swear we don't want any event from it (i.e. next will always fail, just have proc scan)
 		int gvisor_epoll_timeout;	///< When using gvisor, the timeout to wait for a new event
+		struct scap_platform *gvisor_platform; ///< The gvisor engine and platform have a bit of shared state
```
Comment (gnosek) [inline userspace/libscap/engine/gvisor/gvisor_public.h:33]: IMO this needs to be a `scap_gvisor_platform` since we actually depend on the concrete type. Forward-declare the struct type if needed.

Comment (LucaGuerra) [reply userspace/libscap/engine/gvisor/gvisor_public.h]: Makes sense, done!

**Review by loresuso — APPROVED** [review]
lgtm

**Review by Andreagit97 — APPROVED** [review]
/approve

File: userspace/libscap/engine/gvisor/scap_gvisor.cpp [hunk 2]
```diff
@@ -534,8 +553,10 @@ int32_t engine::next(scap_evt **pevent, uint16_t *pdevid, uint32_t *pflags)
 		sandbox_entry &sandbox = it->second;
 		if(sandbox.m_closing)
 		{
+			std::string container_id = sandbox.m_container_id;
```
Comment (FedeDP) [inline userspace/libscap/engine/gvisor/scap_gvisor.cpp:556]: Shouldn't this be `sandbox.m_id`? 
I mean, `release_sandbox_id` takes the sandbox id as argument...

Comment (LucaGuerra) [reply userspace/libscap/engine/gvisor/scap_gvisor.cpp:556]: The names are a little confusing I understand, but the `container_id` is the string which is the one that `release_sandbox_id` takes as parameter

**Review by FedeDP — APPROVED** [review]
/approve
