### PR TITLE
fix(driver): use correct syntax for flexible array member

### LINKED ISSUE #2752: UBSAN: array-index-out-of-bounds in main.c:860:27
maybe, it better belongs here to be reported !?

https://github.com/draios/sysdig/issues/2175

csysdig seem to trigger ubsan error message. 

if i see this correct, ubsan is some tool to detect bugs in c-code in linux kernel ( https://github.com/falcosecurity/libs/issues/979 ) 

if it's not ok to report this way, please let me know and i can make a more in-depth writeup

### PR DESCRIPTION
**Pull request by irozzo-1A**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind test

> /kind feature

> /kind sync

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area API-version

> /area build

> /area CI

/area driver-kmod

> /area driver-bpf

> /area driver-modern-bpf

> /area libscap-engine-bpf

> /area libscap-engine-gvisor

> /area libscap-engine-kmod

> /area libscap-engine-modern-bpf

> /area libscap-engine-nodriver

> /area libscap-engine-noop

> /area libscap-engine-source-plugin

> /area libscap-engine-savefile

> /area libscap

> /area libpman

> /area libsinsp

> /area tests

> /area proposals

**Does this PR require a change in the driver versions?**

> /version driver-API-version-major

> /version driver-API-version-minor

> /version driver-API-version-patch

> /version driver-SCHEMA-version-major

> /version driver-SCHEMA-version-minor

> /version driver-SCHEMA-version-patch

**What this PR does / why we need it**:

UBSAN (Undefined Behaviour Sanitizer) performs compile-time and runtime checks based on declared array bounds. Flaxible Array Member used to be declared with the `[0]` syntax, but should now be expressed with `[]` syntax to respect C99 standard (§6.7.2.1).

**Which issue(s) this PR fixes**:

Fixes #2752 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fix(driver): address UBSAN violation related to Flexible Array Member.
```

### CODE REVIEW

File: driver/ppm_events_public.h [hunk 1]
```diff
@@ -2299,7 +2299,7 @@ struct ppm_proc_info {
 struct ppm_proclist_info {
 	int64_t n_entries;
 	int64_t max_entries;
-	struct ppm_proc_info entries[0];
+	struct ppm_proc_info entries[];
```
Comment (terror96) [inline driver/ppm_events_public.h:2302]: Good catch, indeed '[]' is the modern, more portable way to define flexible arrays.

**Comment by irozzo-1A** [comment]
https://github.com/falcosecurity/libs/actions/runs/20261424717/job/58174173864?pr=2760 is a false positive, this change does not affect the SCHEMA_VERSION

**Review by ekoops — APPROVED** [review]
/approve
