### PR TITLE
Users and groups loading code fixes

### LINKED ISSUE #19: filterchecks.cpp with assertion uinfo != _null failed error
**Describe the bug**
After running `falco` command for a while, it aborts and outputs:
```
falco: /home/nitroc/falco/build/sysdig-repo/sysdig-prefix/src/sysdig/userspace/libsinsp/filterchecks.cpp:4617: virtual uint8_t* sinsp_filter_check_user::extract(sinsp_evt*, uint32_t*, bool): Assertion `uinfo != __null' failed.
```

**How to reproduce it**

Follow the `Getting Started` guide and build Falco from source code.

**Expected behaviour**

Run as normal without abortion.

**Screenshots**

image

**Environment**

- Falco version:

```
Falco version: 0.27.0
Driver version: 5c0b863ddade7a45568c0ac97d037422c9efb750
```
- Build Params:
```
-DBUILD_BPF=ON -DCMAKE_BUILD_TYPE=Debug
```
- System info:

image
- Cloud provider or hardware configuration:
- OS: Latest Arch Linux

- Kernel: 5.4.84-1-lts

- Installation method: from source

**Additional context**

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area libscap
/area libsinsp

**What this PR does / why we need it**:

Fix weird edge cases where users/groups where added while libscap was loading them, potentially causing a segfault.
Moreover, a sinsp::get_group() api is added, following  sinsp::get_user(), and used where needed. 

Interesting fact: libscap only loads the list of users once, during startup; thus the list of users is static, and not dynamically updated. 
This means that when filtering on a user {name,homedir,shell,loginname} (and the same goes for a group name), events for new users won't be actually managed.

Steps to reproduce the abort in #19: 

* build libs in debug mode
* using sysdig tool linking debug-mode-libs, start with an user filter, eg: `sudo ./userspace/sysdig/sysdig "user.name=foo"`
* on another shell, add a new user (name does not matter): `sudo useradd bar` 
* now let's run eg: `sudo -u bar echo test`
* see sysdig aborting with `sysdig: libs/userspace/libsinsp/filterchecks.cpp:4619: virtual uint8_t* sinsp_filter_check_user::extract(sinsp_evt*, uint32_t*, bool): Assertion `uinfo != __null' failed.`
 
In release mode, the crash is not triggered, but the filter is doing nothing for newly created users, eg running:
`sudo ./userspace/sysdig/sysdig "user.name=foo"`
and then creating a foo user and let it doing stuff, won't trigger any output.

**Which issue(s) this PR fixes**:

Fixes #19 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
Rebased on master.

**Comment by leogr** [comment]
Closing and reopening to trigger the CI
/close

File: userspace/libscap/scap_userlist.c [hunk 1]
```diff
@@ -31,8 +31,8 @@ limitations under the License.
 //
 int32_t scap_create_userlist(scap_t* handle)
 {
-	uint32_t usercnt;
-	uint32_t grpcnt;
+	uint32_t usercnt, useridx;
+	uint32_t grpcnt, grpidx;
```
Comment (gnosek) [inline userspace/libscap/scap_userlist.c:35]: Honestly, I'd rather we dropped the double walk over all users/groups.

We're saving some time allocating but spend potentially a lot more talking to nss (if e.g. the user database is in ldap, enumerating all users may be very slow).

I think we can just realloc() the table to double the size when we run out of space and then realloc() it back to the exact size once we finish enumerating users/groups.

File: userspace/libsinsp/filterchecks.cpp [hunk 2]
```diff
@@ -4832,23 +4833,7 @@ uint8_t* sinsp_filter_check_group::extract(sinsp_evt *evt, OUT uint32_t* len, bo
...
-
-			it = grouplist->find(tinfo->m_gid);
-			if(it == grouplist->end())
-			{
-				ASSERT(false);
-				return NULL;
-			}
-
-			scap_groupinfo* ginfo = it->second;
+			auto ginfo = m_inspector->get_group(tinfo->m_gid);
```
Comment (gnosek) [inline userspace/libsinsp/filterchecks.cpp:4836]: It's completely legit if a gid doesn't map to a group name (even if our nss cache was up to date) so I don't think we should ASSERT below but just treat the group name as empty (or something like this, maybe "<NA>"?)

A nullptr is doubly valid since you do the gid == -1 check inside the method

File: userspace/libsinsp/filterchecks.cpp [hunk 3]
```diff
@@ -4777,6 +4777,7 @@ uint8_t* sinsp_filter_check_user::extract(sinsp_evt *evt, OUT uint32_t* len, boo
 	case TYPE_LOGINNAME:
 		ASSERT(m_inspector != NULL);
 		uinfo = m_inspector->get_user(tinfo->m_loginuid);
+		ASSERT(uinfo != NULL);
```
Comment (gnosek) [inline userspace/libsinsp/filterchecks.cpp:4780]: Same as for the group name. Not having a name for a uid is maybe unexpected but certainly not a crash-worthy error. So the ASSERT in line 4758 is wrong too IMHO.

Also, loginuid can easily be -1.

File: userspace/libscap/scap_userlist.c [hunk 4]
```diff
@@ -97,74 +97,100 @@ int32_t scap_create_userlist(scap_t* handle)
...
 		{
-			*handle->m_userlist->groups[grpcnt].name = '\0';
+			*group->name = '\0';
 		}
 
 		handle->m_userlist->totsavelen += 
 			sizeof(uint8_t) + // type
-			sizeof(uint32_t) +  // gid
-			strlen(handle->m_userlist->groups[grpcnt].name) + 2;
+			sizeof(group->gid) +
```
Comment (gnosek) [inline userspace/libscap/scap_userlist.c:176]: This makes it so group->gid *must* be 32 bits to avoid breaking scap files, right?

Though I expect we probably just dump the struct directly when writing a scap so this assumption is already there, but still. So I'd say both the old and new version is bad but for different reasons and the fix would involve changes in the savefile code)

(same goes for the uid change above)

File: .gitignore [hunk 5]
```diff
@@ -23,3 +23,4 @@ driver/driver_config.h
 .vscode
 .cache.mk
 build*
+.idea
```
Comment (gnosek) [inline .gitignore:26]: Not sure this belongs in this particular PR :)

File: userspace/libsinsp/sinsp.h [hunk 6]
```diff
@@ -491,7 +491,7 @@ class SINSP_PUBLIC sinsp : public capture_stats_source, public wmi_handle_source
 	threadinfo_map_t::ptr_t get_thread_ref(int64_t tid, bool query_os_if_not_found = false, bool lookup_only = true, bool main_thread = false);
 
 	/*!
-	  \brief Return the table with all the machine users.
+  	  \brief Return the table with all the machine users.
```
Comment (gnosek) [inline userspace/libsinsp/sinsp.h:494]: I honestly don't know if this breaks the indentation or fixes it ;)

**Comment by FedeDP** [comment]
Thanks for the review @gnosek ! 
Will fix asap :)

**Comment by FedeDP** [comment]
@gnosek should've addressed all the open points!

**Review by gnosek — APPROVED** [review]
Thanks!

**Review by mstemm — APPROVED** [review]

**Review by leogr — APPROVED** [review]
/approve
