### PR TITLE
fix(userspace/libscap): avoid possible double free while loading users and groups

### LINKED ISSUE #1312: double free in some scenarios
**Describe the bug**
https://github.com/falcosecurity/libs/blob/master/userspace/libscap/linux/scap_userlist.c#L297
if `grpidx` is 0, then realloc size is 0. such as getgrent failed.

https://linux.die.net/man/3/realloc
If size was equal to 0, either NULL or a pointer suitable to be passed to free() is returned

https://github.com/falcosecurity/libs/blob/master/userspace/libscap/linux/scap_userlist.c#L302
then free(userlist->groups) will cause double free.

**How to reproduce it**

**Expected behaviour**

**Screenshots**

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method: source

**Additional context**

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area libscap

**Does this PR require a change in the driver versions?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #1312

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fix: avoid possible source of double free
```

### CODE REVIEW

File: userspace/libscap/linux/scap_userlist.c [hunk 1]
```diff
@@ -197,12 +197,14 @@ int32_t scap_linux_create_userlist(struct scap_platform* platform)
...
 
+	// if userIdx == 0 -> realloc with size 0 means free, and NULL is returned.
+	// so, we will end up with userlist->nusers = 0 and userlist->users NULL.
 	userlist->nusers = useridx;
 	if (useridx < usercnt)
 	{
 		// Reduce array size
 		scap_userinfo *reduced_userinfos = realloc(userlist->users, useridx * sizeof(scap_userinfo));
-		if(reduced_userinfos == NULL)
+		if(reduced_userinfos == NULL && useridx > 0)
```
Comment (Andreagit97) [inline userspace/libscap/linux/scap_userlist.c:207]: I see that there are other `free(userlist->users);` in this function, is it ok to continue the flow with `userlist->users == null` and `useridx==0`? can we interrupt the flow here if we follow in this condition ?

Comment (FedeDP) [reply userspace/libscap/linux/scap_userlist.c:207]: It's not an error; it just means that there are no users/groups available. 
I think it's a super edge case, but still.
Freeing a NULL ptr it's not an error.

Comment (Andreagit97) [reply userspace/libscap/linux/scap_userlist.c:207]: ok thank you!

**Review by Andreagit97 — APPROVED** [review]
/approve

**Review by jasondellaluce — APPROVED** [review]
/approve
