### PR TITLE
fix(userspace/libsinsp/parsers): guard against invalid cmsg_len values

### LINKED ISSUE #2765: Align `ppm_cmsg_nxthdr` with glibc `__cmsg_nxthdr`
**Describe the bug**

One possible bug related to `ppm_cmsg_nxthdr` implementation was discovered and fixed in https://github.com/falcosecurity/libs/pull/2764 .

`ppm_cmsg_nxthdr` implementation has been equivalent to the official `__cmsg_nxthdr` glibc implementation, but now the two diverge.
We can clearly see from glibc source code that a patch, aiming to introduce additional cmsg length checks, has been delivered starting from version 2.37: https://github.com/bminor/glibc/commit/9c443ac4559a47ed99859bd80d14dc4b6dd220a1

The new checks are not present in the current `ppm_cmsg_nxthdr` implementation, and it would be better to align it with the official one and avoid potentially bogus drifts.

**How to reproduce it**

This highlight potential issues, not yet experienced in real deployments.

**Expected behaviour**

`sinsp_parser` correctly iterates over control messages, and correctly handles malformed ones.

**Screenshots**

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

This highlight potential issues, not yet experienced in real deployments.

**Additional context**

### PR DESCRIPTION
**Pull request by ekoops**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind test

> /kind feature

> /kind sync

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area API-version

> /area build

> /area CI

> /area driver-kmod

> /area driver-bpf

> /area driver-modern-bpf

> /area libscap-engine-bpf

> /area libscap-engine-gvisor

> /area libscap-engine-kmod

> /area libscap-engine-modern-bpf

> /area libscap-engine-nodriver

> /area libscap-engine-noop

> /area libscap-engine-source-plugin

> /area libscap-engine-savefile

> /area libscap

> /area libpman

/area libsinsp

> /area tests

> /area proposals

**Does this PR require a change in the driver versions?**

> /version driver-API-version-major

> /version driver-API-version-minor

> /version driver-API-version-patch

> /version driver-SCHEMA-version-major

> /version driver-SCHEMA-version-minor

> /version driver-SCHEMA-version-patch

**What this PR does / why we need it**:

This PR guards against invalid `cmsg_len` values while accessing control messages in ancillary data. This is achieved by checking there is enough space between the current control message and the end of the buffer to hold both the current control message and the next one.

This change sync the implementation of `ppm_cmsg_nxthdr()` with the current glibc implementation:
https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/unix/sysv/linux/cmsg_nxthdr.c;h=0e602a16053ed6742ea1556d75de8540e49157f1;hb=170550da27f68a08589e91b541883dcc58dee640

**Which issue(s) this PR fixes**:

Fixes #2765 

**Special notes for your reviewer**:

/milestone 0.24.0

This also handles the case in https://github.com/falcosecurity/libs/pull/2764 . To understand why, let's analyze the scenario with the new implementation. In the following, I'm assuming `sizeof(size_t) => 8`, so `sizeof(cmsghdr) => 16`.

Given `cmsg_len => 0xFFFFFFFFFFFFFFFF`, then `__CMSG_PADDING(cmsg_len) => 1`, so `size_needed => sizeof(size_t) + __CMSG_PADDING(cmsg_len) => 17`.

Now, `remaining_room` is defined as the distance between the beginning of the current control message and the end of all control messages. It is defined in the following way:
```c
const size_t remaining_room = static_cast<size_t>(msg_control + msg_controllen - reinterpret_cast<char *>(cmsg));
```

Notice that this value is positive, because `cmsg` is by construction a pointer laying on the region `[msg_control, msg_control + msg_controllen].`

We detect two failing cases:
- `remaining_room < size_needed` - not important for this analysis
- `remaining_room - size_needed < cmsg_len` - notice that this case is evaluated only if `remaining_room >= size_needed`; this means that must always be `remaining_room - size_needed >= 0`. For our analysis, here we have `something positive < 0xFFFFFFFFFFFFFFFF`, which is clearly true, preventing returning a non-NULL value

Hope this analysis helps reviewers.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ekoops** [comment]
CC @fremmi , @deepskyblue86 , @terror96

File: userspace/libsinsp/parsers.cpp [hunk 1]
```diff
@@ -3191,17 +3196,18 @@ static ppm_cmsghdr *ppm_cmsg_nxthdr(char const *msg_control,
...
 
-	size_t const cmsg_aligned_len = PPM_CMSG_ALIGN(cmsg_len);
-	// Guard against infinite loop: ensure we advance by at least sizeof(ppm_cmsghdr)
-	if(cmsg_aligned_len < sizeof(ppm_cmsghdr)) {
-		return nullptr;
-	}
-	cmsg = reinterpret_cast<ppm_cmsghdr *>(reinterpret_cast<char *>(cmsg) + cmsg_aligned_len);
-	if(reinterpret_cast<char *>(cmsg + 1) > msg_control + msg_controllen ||
-	   reinterpret_cast<char *>(cmsg) + cmsg_aligned_len > msg_control + msg_controllen) {
+	// There isn't enough space between cmsg and the end of the buffer to hold the current cmsg
```
Comment (terror96) [inline userspace/libsinsp/parsers.cpp]:
```suggestion
	// Check that there is enough space between cmsg and the end of the buffer to hold the current cmsg
```

**Review by irozzo-1A — DISMISSED** [review]
/lgtm

File: userspace/libsinsp/parsers.cpp (hunk 1 above)
Comment (ekoops) [reply userspace/libsinsp/parsers.cpp]: Thank you @terror96 . I'm gonna fix it.

**Review by terror96 — APPROVED** [review]
/lgtm
