### PR TITLE
fix(sinsp): fix `fs.path` filterchecks for relative paths (add `dirfd` concept)

### LINKED ISSUE #2039: Fix fd filtercheck fallback in case of  `openat*` events involving `dirfd` parsing
Follow up to https://github.com/falcosecurity/libs/pull/1993#discussion_r1738462593

I believe we need another small fix in another PR for the fd filtercheck fallback in case of  `openat*` events involving `dirfd` parsing ...

https://github.com/falcosecurity/libs/blob/5ed00b2a9a627d9a6263369edfdcbaf5cc6b1485/userspace/libsinsp/sinsp_filtercheck_fd.cpp#L242

aka since we do change the state (as @LucaGuerra helped pointing out) it seems to me that we also need to rewrite the fd info with all concatenated paths etc to the cache, similar to the parsers logic here: https://github.com/falcosecurity/libs/blob/5ed00b2a9a627d9a6263369edfdcbaf5cc6b1485/userspace/libsinsp/parsers.cpp#L2784

---

Plus there are not many `fd.name` unit tests. In this PR https://github.com/falcosecurity/libs/pull/1993 we introduce a wider test scope for `fs.path.*` fields and also compare them to the `fd.name` field if applicable.

CC @LucaGuerra thanks a bunch in advance!

### PR DESCRIPTION
**Pull request by incertum**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area API-version

> /area build

> /area CI

> /area driver-kmod

> /area driver-bpf

> /area driver-modern-bpf

> /area libscap-engine-bpf

> /area libscap-engine-gvisor

> /area libscap-engine-kmod

> /area libscap-engine-modern-bpf

> /area libscap-engine-nodriver

> /area libscap-engine-noop

> /area libscap-engine-source-plugin

> /area libscap-engine-savefile

> /area libscap

> /area libpman

/area libsinsp

> /area tests

> /area proposals

**Does this PR require a change in the driver versions?**

> /version driver-API-version-major

> /version driver-API-version-minor

> /version driver-API-version-patch

> /version driver-SCHEMA-version-major

> /version driver-SCHEMA-version-minor

> /version driver-SCHEMA-version-patch

**What this PR does / why we need it**:

While working on the anomalydetection plugin i was looking into the fd fallbacks and noticed that there are a few cases off in libs.
- `fs.path` fields incorrectly do not incorporate the concept of `dirfd` and as such they differ from the more correct `fd.name` value if applicable.
- Missing `dirfd` handling for `PPME_SYSCALL_OPEN_BY_HANDLE_AT_X` throughout.

@LucaGuerra and @FedeDP (when you are back), could you help take a look? We all were involved in recent fixes in these areas. Thank you.
CC @mstemm 

@leogr these fixes will result in subtle semantic changes of the affected filtercheck fields. Please note that these changes are corrections meaning the current values are off in the here addressed cases.

Currently still in WIP as I need more time to seriously improve our test cases throughout.

**Which issue(s) this PR fixes**:

Fixes #2039

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: userspace/libsinsp/parsers.cpp [hunk 1]
```diff
@@ -2732,8 +2732,8 @@ void sinsp_parser::parse_open_openat_creat_exit(sinsp_evt *evt)
 			}
 		}
 
-		// since open_by_handle_at returns an absolute path we will always start at /
```
Comment (incertum) [inline userspace/libsinsp/parsers.cpp:2735]: Not correct, see https://man7.org/linux/man-pages/man2/open_by_handle_at.2.html

File: userspace/libsinsp/sinsp_filtercheck_fspath.cpp [hunk 2]
```diff
@@ -355,10 +355,100 @@ uint8_t* sinsp_filter_check_fspath::extract_single(sinsp_evt* evt, uint32_t* len
 
 		if(!std::filesystem::path(m_tstr).is_absolute())
 		{
-			m_tstr = sinsp_utils::concatenate_paths(tinfo->get_cwd(), m_tstr);
+			std::string sdir; // init
+			// Compare to `sinsp_filter_check_fd::extract_fdname_from_creator` logic
```
Comment (incertum) [inline userspace/libsinsp/sinsp_filtercheck_fspath.cpp:359]: Sharing the relevant event I grepped out for easier review if the param number is correct

```
[PPME_SYSCALL_UNLINKAT_2_X] = {"unlinkat", EC_FILE | EC_SYSCALL, EF_NONE, 4, {{"res", PT_ERRNO, PF_DEC}, {"dirfd", PT_FD, PF_DEC}, {"name", PT_FSRELPATH, PF_NA, DIRFD_PARAM(1)}, {"flags", PT_FLAGS32, PF_HEX, unlinkat_flags} } },
[PPME_SYSCALL_MKDIRAT_X] = {"mkdirat", EC_FILE | EC_SYSCALL, EF_NONE, 4, {{"res", PT_ERRNO, PF_DEC}, {"dirfd", PT_FD, PF_DEC}, {"path", PT_FSRELPATH, PF_NA, DIRFD_PARAM(1)}, {"mode", PT_UINT32, PF_HEX} } },
[PPME_SYSCALL_OPENAT_2_X] = {"openat", EC_FILE | EC_SYSCALL, EF_CREATES_FD | EF_MODIFIES_STATE, 7, {{"fd", PT_FD, PF_DEC}, {"dirfd", PT_FD, PF_DEC}, {"name", PT_FSRELPATH, PF_NA, DIRFD_PARAM(1)}, {"flags", PT_FLAGS32, PF_HEX, file_flags}, {"mode", PT_UINT32, PF_OCT}, {"dev", PT_UINT32, PF_HEX}, {"ino", PT_UINT64, PF_DEC} } },
[PPME_SYSCALL_FCHMODAT_X] = {"fchmodat", EC_FILE | EC_SYSCALL, EF_NONE, 4, {{"res", PT_ERRNO, PF_DEC}, {"dirfd", PT_FD, PF_DEC}, {"filename", PT_FSRELPATH, PF_NA, DIRFD_PARAM(1)}, {"mode", PT_MODE, PF_OCT, chmod_mode} } },
[PPME_SYSCALL_OPENAT2_X] = {"openat2", EC_FILE | EC_SYSCALL, EF_CREATES_FD | EF_MODIFIES_STATE, 8, {{"fd", PT_FD, PF_DEC}, {"dirfd", PT_FD, PF_DEC}, {"name", PT_FSRELPATH, PF_NA, DIRFD_PARAM(1)}, {"flags", PT_FLAGS32, PF_HEX, file_flags}, {"mode", PT_UINT32, PF_OCT}, {"resolve", PT_FLAGS32, PF_HEX, openat2_flags}, {"dev", PT_UINT32, PF_HEX}, {"ino", PT_UINT64, PF_DEC} } },
[PPME_SYSCALL_FCHOWNAT_X] = {"fchownat", EC_FILE | EC_SYSCALL, EF_NONE, 6, {{"res", PT_ERRNO, PF_DEC}, {"dirfd", PT_FD, PF_DEC}, {"pathname", PT_FSRELPATH, PF_NA, DIRFD_PARAM(1)}, {"uid", PT_UINT32, PF_DEC}, {"gid", PT_UINT32, PF_DEC}, {"flags", PT_FLAGS32, PF_HEX, fchownat_flags}} },
[PPME_SYSCALL_MKNODAT_X] = {"mknodat", EC_OTHER | EC_SYSCALL, EF_USES_FD, 5, {{"res", PT_ERRNO, PF_DEC}, {"dirfd", PT_FD, PF_DEC}, {"path", PT_FSRELPATH, PF_NA, DIRFD_PARAM(1)},{"mode", PT_MODE, PF_OCT, mknod_mode},{"dev", PT_UINT32, PF_DEC}}},
[PPME_SYSCALL_NEWFSTATAT_X] = {"newfstatat", EC_FILE | EC_SYSCALL, EF_USES_FD, 4, {{"res", PT_ERRNO, PF_DEC}, {"dirfd", PT_FD, PF_DEC}, {"path", PT_FSRELPATH, PF_NA, DIRFD_PARAM(1)}, {"flags", PT_FLAGS32, PF_HEX, newfstatat_flags}}},


[PPME_SYSCALL_OPENAT_2_E] = {"openat", EC_FILE | EC_SYSCALL, EF_CREATES_FD | EF_MODIFIES_STATE, 4, {{"dirfd", PT_FD, PF_DEC}, {"name", PT_FSRELPATH, PF_NA, DIRFD_PARAM(0)}, {"flags", PT_FLAGS32, PF_HEX, file_flags}, {"mode", PT_UINT32, PF_OCT} } },
[PPME_SYSCALL_OPENAT2_E] = {"openat2", EC_FILE | EC_SYSCALL, EF_CREATES_FD | EF_MODIFIES_STATE, 5, {{"dirfd", PT_FD, PF_DEC}, {"name", PT_FSRELPATH, PF_NA, DIRFD_PARAM(1)}, {"flags", PT_FLAGS32, PF_HEX, file_flags}, {"mode", PT_UINT32, PF_OCT}, {"resolve", PT_FLAGS32, PF_HEX, openat2_flags} } },


[PPME_SYSCALL_RENAMEAT2_X] = {"renameat2", EC_FILE | EC_SYSCALL, EF_NONE, 6, {{"res", PT_ERRNO, PF_DEC}, {"olddirfd", PT_FD, PF_DEC}, {"oldpath", PT_FSRELPATH, PF_NA, DIRFD_PARAM(1)}, {"newdirfd", PT_FD, PF_DEC}, {"newpath", PT_FSRELPATH, PF_NA, DIRFD_PARAM(3)}, {"flags", PT_FLAGS32, PF_HEX, renameat2_flags} } },

[PPME_SYSCALL_SYMLINKAT_X] = {"symlinkat", EC_FILE | EC_SYSCALL, EF_NONE, 4, {{"res", PT_ERRNO, PF_DEC}, {"target", PT_CHARBUF, PF_NA}, {"linkdirfd", PT_FD, PF_DEC}, {"linkpath", PT_FSRELPATH, PF_NA, DIRFD_PARAM(2)} } },

[PPME_SYSCALL_OPEN_BY_HANDLE_AT_X] = {"open_by_handle_at", EC_FILE | EC_SYSCALL, EF_CREATES_FD | EF_MODIFIES_STATE, 6, {{"fd", PT_FD, PF_DEC}, {"mountfd", PT_FD, PF_DEC}, {"flags", PT_FLAGS32, PF_HEX, file_flags}, {"path", PT_FSPATH, PF_NA}, {"dev", PT_UINT32, PF_HEX}, {"ino", PT_UINT64, PF_DEC} } },
```

As mentioned in the PR all still WIP since I need to expand the unit tests ...

**Review by Andreagit97 — COMMENTED** [review]
Ei! Just an early feedback on open_by_handle_at syscall management

File: userspace/libsinsp/parsers.cpp [hunk 3]
```diff
@@ -2732,8 +2732,8 @@ void sinsp_parser::parse_open_openat_creat_exit(sinsp_evt *evt)
...
-		sdir = "";
+		int64_t dirfd_mountfd = evt->get_param(1)->as<int64_t>(); // mountfd
```
[the remark this answers is not in the document]
Comment (incertum) [reply userspace/libsinsp/parsers.cpp:2735]: Hah of course why not ... I wasn't aware how fragmented our open* approaches truly are and that we even do dpath traversals for open by handle at in the kernel ... one of these days I'll try to compile a few things in an issue, but it's not urgent for the upcoming release.

File: userspace/libsinsp/test/events_fspath.ut.cpp [hunk 4]
```diff
@@ -104,6 +107,13 @@ class fspath : public sinsp_with_test_input
 		ASSERT_FALSE(field_has_value(evt, fs_path_targetraw));
 	}
 
+	void verify_fd_name_same_fs_path_name(sinsp_evt *evt)
+	{
+		// todo the cached fd.name might be subject to some std::string_view lifetime issues as the second path of the path concatenation
+		// is missing when retrieving fd.name from the cache. Let's check if string_view and std::string handling is done correctly throughout.
+		// ASSERT_STREQ(get_field_as_string(evt, fs_path_name).c_str(), get_field_as_string(evt, "fd.name").c_str());
```
Comment (incertum) [inline userspace/libsinsp/test/events_fspath.ut.cpp:114]: @falcosecurity/libs-maintainers and also @federico-sysdig would appreciate some help to resolve some mystery (again) ....

So these tests (comparing the `fd.name` from the cache to the `fs.path.name`) are failing, possibly due to some std::string_view lifetime issues or other issues? Regardless am stuck debugging.

Sprinkled few print statements along the relevant code paths and we only loose the second part of the concatenated path when retrieving the name from the cache in the fd filterchecks. Before that it's all correct within the parsers logic.

```
[ RUN      ] fspath.openat_2_relative
parser name exit tmp/random/dir...///../../name.txt
parser name enter event tmp/random/dir...///../../name.txt
parser name fullpath /tmp/dirfd1/dirfd2/dirfd3/dirfd4/dirfd5/dirfd6/dirfd7/dirfd8/tmp/name.txt
parser name fullpath from fdi /tmp/dirfd1/dirfd2/dirfd3/dirfd4/dirfd5/dirfd6/dirfd7/dirfd8/tmp/name.txt
parser name fullpath from table cache fdi /tmp/dirfd1/dirfd2/dirfd3/dirfd4/dirfd5/dirfd6/dirfd7/dirfd8/tmp/name.txt
FDNAME fd 3 CACHE FILTERCHECK /tmp/dirfd1/dirfd2/dirfd3/dirfd4/dirfd5/dirfd6/dirfd7/dirfd8
```

[Btw the fallback in the filtercheck `extract_from_null_fd` is working as expected and these tests would pass.  Also note that today we do not test `fd.name` for many scenarios ...]

Comment (federico-sysdig) [reply userspace/libsinsp/test/events_fspath.ut.cpp:114]: I don't understand. Are you saying that you get a full path when using `get_field_as_string(evt, fs_path_name)` and only the first part of it when using `get_field_as_string(evt, "fd.name")`? Should they really be equal? Wouldn't it depend on the value of `fs_path_name`?
If there is an issue with a string view pointing at a string whose lifetime is over, that is indeed a serious issue, but it would be a problem within the machinery behind `get_field_as_string`.

Nit: The check can be a bit simpler:
```c++
ASSERT_EQ(get_field_as_string(evt, fs_path_name), get_field_as_string(evt, "fd.name"));
```

Comment (incertum) [reply userspace/libsinsp/test/events_fspath.ut.cpp]: (1) Incorporated your nit suggestion  and also made sure the list of events where these 2 should be same is complete. Re-pushed the last commit.

(2) Plus let me share the 2 locations in the source code where the cached string that represents the fd full file path is not equal. 

- https://github.com/falcosecurity/libs/blob/874e573b20178325ebe483af7f104ae3c70fdf34/userspace/libsinsp/sinsp_filtercheck_fd.cpp#L520 which is `m_tstr = m_fdinfo->m_name;` has the second part of the paths that were concatenated missing
- Versus in the parsers https://github.com/falcosecurity/libs/blob/874e573b20178325ebe483af7f104ae3c70fdf34/userspace/libsinsp/parsers.cpp#L2776 `m_name`  is correct, also when directly retrieving it again after having written it to the fd table / cache.

See below a print output for how https://github.com/falcosecurity/libs/blob/874e573b20178325ebe483af7f104ae3c70fdf34/userspace/libsinsp/sinsp_filtercheck_fd.cpp#L520 `m_tstr = m_fdinfo->m_name;` looks like atm.

```
[ RUN      ] fspath.open

FILTERCHECK FDNAME FROM FD CACHE /tmp/name

[       OK ] fspath.open (0 ms)
[ RUN      ] fspath.openat
[       OK ] fspath.openat (0 ms)
[ RUN      ] fspath.openat_2
FILTERCHECK FDNAME FROM FD CACHE /tmp/name
[       OK ] fspath.openat_2 (0 ms)
[ RUN      ] fspath.openat_2_relative

FILTERCHECK FDNAME FROM FD CACHE /tmp/dirfd1/dirfd2/dirfd3/dirfd4/dirfd5/dirfd6/dirfd7/dirfd8

/home/m/Documents/OSS/oss-dev-master/libs/userspace/libsinsp/test/events_fspath.ut.cpp:114: Failure
Expected equality of these values:
  get_field_as_string(evt, fs_path_name)
    Which is: "/tmp/dirfd1/dirfd2/dirfd3/dirfd4/dirfd5/dirfd6/dirfd7/dirfd8/tmp/name.txt"
  get_field_as_string(evt, "fd.name")
    Which is: "/tmp/dirfd1/dirfd2/dirfd3/dirfd4/dirfd5/dirfd6/dirfd7/dirfd8"
[  FAILED  ] fspath.openat_2_relative (0 ms)
[ RUN      ] fspath.openat2

FILTERCHECK FDNAME FROM FD CACHE /tmp/name

[       OK ] fspath.openat2 (0 ms)
[ RUN      ] fspath.openat2_relative

FILTERCHECK FDNAME FROM FD CACHE /tmp/dirfd1/dirfd2/dirfd3/dirfd4/dirfd5/dirfd6/dirfd7/dirfd8

/home/m/Documents/OSS/oss-dev-master/libs/userspace/libsinsp/test/events_fspath.ut.cpp:114: Failure
Expected equality of these values:
  get_field_as_string(evt, fs_path_name)
    Which is: "/tmp/dirfd1/dirfd2/dirfd3/dirfd4/dirfd5/dirfd6/dirfd7/dirfd8/tmp/name.txt"
  get_field_as_string(evt, "fd.name")
    Which is: "/tmp/dirfd1/dirfd2/dirfd3/dirfd4/dirfd5/dirfd6/dirfd7/dirfd8"
[  FAILED  ] fspath.openat2_relative (0 ms)
[ RUN      ] fspath.openat2_relative_dirfd_cwd
```

Comment (LucaGuerra) [reply userspace/libsinsp/test/events_fspath.ut.cpp]: I'm taking a look at this. I tried pulling your branch, rebasing it and running the tests but this one doesn't seem to be failing. Did you happen to remove the failing one?

Comment (incertum) [reply userspace/libsinsp/test/events_fspath.ut.cpp]: The failing test is commented out for now.

File: userspace/libsinsp/sinsp_filtercheck_fspath.cpp [hunk 5]
```diff
@@ -355,10 +355,99 @@ uint8_t* sinsp_filter_check_fspath::extract_single(sinsp_evt* evt, uint32_t* len
...
+				case PPME_SYSCALL_FCHOWNAT_X:
+				case PPME_SYSCALL_FCHMODAT_X:
+				case PPME_SYSCALL_MKDIRAT_X:
+				case PPME_SYSCALL_UNLINKAT_2_X:
+				case PPME_SYSCALL_MKNODAT_X:
+				{
+					int64_t dirfd = evt->get_param(1)->as<int64_t>();
+					// `parse_dirfd` checks if path is absolute and if so returns an '.' string to sdir
+					// Function tries to return fd name from the fd stored at dirfd in the fd table
+					sdir = m_inspector->get_parser()->parse_dirfd(evt, m_tstr, dirfd);
```
Comment (LucaGuerra) [inline userspace/libsinsp/sinsp_filtercheck_fspath.cpp:384]: Referring to the comment above, these are the calls that modify the thread state

File: userspace/libsinsp/test/events_fspath.ut.cpp (hunk 4 above)
Comment (incertum) [reply userspace/libsinsp/test/events_fspath.ut.cpp]: Thanks so much :rocket: @LucaGuerra. Pushed a co-authored commit. Feel free to overwrite it if you have a better idea.
Also created a follow ticket here: https://github.com/falcosecurity/libs/issues/2039

The macos test is currently failing ...

File: userspace/libsinsp/sinsp_filtercheck_fspath.cpp [hunk 6]
```diff
@@ -240,6 +240,56 @@ std::unique_ptr<sinsp_filter_check> sinsp_filter_check_fspath::allocate_new()
 	return ret;
 }
 
+std::string sinsp_filter_check_fspath::parse_dirfd_stateless(sinsp_evt *evt, std::string_view name, int64_t dirfd)
```
Comment (FedeDP) [inline userspace/libsinsp/sinsp_filtercheck_fspath.cpp:243]: If i understand correctly, all we need is to skip the `evt->set_fd_info(evt->get_tinfo()->get_fd(dirfd));` call in `parse_dirfd`, right? 
I think we can just add a boolean optional parameter (that of course defaults to `true` to `parse_dirfd`, like:
```
std::string sinsp_parser::parse_dirfd(sinsp_evt *evt, std::string_view name, int64_t dirfd, bool update_tinfo=true)
```
and pass `false` when called from the filterchecks.

Comment (incertum) [reply userspace/libsinsp/sinsp_filtercheck_fspath.cpp:243]: Correct, can do that. Are we sure we want one more if statement in the parsers logic?

**Comment by FedeDP** [comment]
@incertum pushed some changes, let me know wdyt (we can rework/remove the commit in case you don't really like it :D )

* move parsing logic to parsers.cpp instead of parsing dirfd on the fly in filterchecks
* made `parse_dirfd` completely stateless, it does not touch anything now
* added the `PPM_O_DIRECTORY` flag in `events_fspath` when we create a `dirfd` folder, since that flag gets enforced by our drivers
* another notable fix (that was not originally part of this PR): do not store an fdinfo in the event in `sinsp_parser::parse_open_openat_creat_exit` when the syscall failed; previously, the fdinfo related to the dirfd was stored even when the syscall failed. That was wrong.

Also cc @LucaGuerra

File: userspace/libsinsp/parsers.cpp [hunk 7]
```diff
@@ -442,6 +442,33 @@ void sinsp_parser::process_event(sinsp_evt *evt)
 	case PPME_SYSCALL_PRCTL_X:
 		parse_prctl_exit_event(evt);
 		break;
+	case PPME_SYSCALL_NEWFSTATAT_X:
```
Comment (FedeDP) [inline userspace/libsinsp/parsers.cpp:445]: New parsers. I didn't add new methods for these small parsers.
Only parse when event are successful, and store in the event fdinfo the `dirfd` related `fdinfo` (that is already present in the thread table since it was previously added by an `open` related syscall)

File: userspace/libsinsp/parsers.cpp [hunk 8]
```diff
@@ -2307,6 +2334,12 @@ void sinsp_parser::parse_execve_exit(sinsp_evt *evt)
 				*/
 				std::string sdir = parse_dirfd(evt, pathname, dirfd);
 
+				// Update event fdinfo since parse_dirfd is stateless
+				if (sdir != "." && sdir != "<UNKNOWN>")
```
Comment (FedeDP) [inline userspace/libsinsp/parsers.cpp:2338]: Since `parse_dirfd` is now stateless, honor previous behavior by setting the fdinfo when needed (ie: when previous logic set it)

File: userspace/libsinsp/test/events_fspath.ut.cpp [hunk 9]
```diff
@@ -181,10 +203,28 @@ class fspath : public sinsp_with_test_input
...
+		{
+			case PPME_SYSCALL_OPENAT_2_X:
+			case PPME_SYSCALL_OPENAT2_X:
+			case PPME_SYSCALL_FCHMODAT_X:
+			case PPME_SYSCALL_FCHOWNAT_X:
+			case PPME_SYSCALL_UNLINKAT_2_X:
+				{
+					add_event_advance_ts(increasing_ts(), 1, PPME_SYSCALL_OPENAT2_E, 2, evt_dirfd, dirfd_path);
+					// pass PPM_O_DIRECTORY since we are creating a folder!
+					add_event_advance_ts(increasing_ts(), 1, PPME_SYSCALL_OPENAT2_X, 5, evt_dirfd, evt_dirfd, dirfd_path, open_flags | PPM_O_DIRECTORY, mode);
```
Comment (FedeDP) [inline userspace/libsinsp/test/events_fspath.ut.cpp:217]: We are creating a folder, enforce `PPM_O_DIRECTORY` otherwise our `fdinfo` will be off.

File: userspace/libsinsp/test/events_fspath.ut.cpp [hunk 10]
```diff
@@ -196,10 +236,23 @@ class fspath : public sinsp_with_test_input
...
 		va_start(args, n);
-		sinsp_evt* evt = add_event_advance_ts_v(increasing_ts(), 1, event_type, n, args);
+		sinsp_evt* evt;
+		switch (event_type)
+		{
+			case PPME_SYSCALL_LINKAT_2_X:
+			case PPME_SYSCALL_SYMLINKAT_X:
+				{
+					add_event_advance_ts(increasing_ts(), 1, PPME_SYSCALL_OPENAT2_E, 2, evt_dirfd, dirfd_path);
+					add_event_advance_ts(increasing_ts(), 1, PPME_SYSCALL_OPENAT2_X, 5, evt_dirfd, evt_dirfd, dirfd_path, open_flags | PPM_O_DIRECTORY, mode);
```
Comment (FedeDP) [inline userspace/libsinsp/test/events_fspath.ut.cpp:246]: We are creating a folder, enforce `PPM_O_DIRECTORY` otherwise our `fdinfo` will be off.

**Comment by incertum** [comment]
> @incertum pushed some changes, let me know wdyt (we can rework/remove the commit in case you don't really like it :D )
> 
> * move parsing logic to parsers.cpp instead of parsing dirfd on the fly in filterchecks
> * made `parse_dirfd` completely stateless, it does not touch anything now
> * added the `PPM_O_DIRECTORY` flag in `events_fspath` when we create a `dirfd` folder, since that flag gets enforced by our drivers
> * another notable fix (that was not originally part of this PR): do not store an fdinfo in the event in `sinsp_parser::parse_open_openat_creat_exit` when the syscall failed; previously, the fdinfo related to the dirfd was stored even when the syscall failed. That was wrong.
> 
> Also cc @LucaGuerra that helped me!

Incredible work @FedeDP and @LucaGuerra, also thanks a lot for jumping in as we need this wrapped up soon.
Still up for discussion if we want to address https://github.com/falcosecurity/libs/issues/2039 here or in another PR or later.

Changes LGTM!

**Comment by FedeDP** [comment]
> Still up for discussion if we want to address https://github.com/falcosecurity/libs/issues/2039 here or in another PR or later.

Aswered over there, imho there is no issue anymore since `parse_dirfd` is now stateless.

**Comment by incertum** [comment]
Nice @LucaGuerra thanks for adding more tests!

**Review by FedeDP — APPROVED** [review]
/approve

**Review by LucaGuerra — APPROVED** [review]
